### ISSUE TITLE
I think you should add a way to uninstall everything, just in case something bad happens.

### ISSUE THREAD

**Issue by tiagaoalb** [Axarva/dotfiles-2.0#100]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Arch Linux]

**Additional context**

**Comment by Axarva** [comment]
An uninstall script, if created, might wipe out your current configs too. In addition, restoring your old configs might be even harder. If you have any suggestions I’m open to listen to them.

**Comment by notprash** [comment]
You can try to put the old config a folder called old config ig

**Comment by tiagaoalb** [comment]
Thank you guys. Great job here 👍🏻

**Comment by Axarva** [comment]
> You can try to put the old config a folder called old config ig

The install script does this… hm, maybe I’ll add an uninstall script soon. Although uninstalling the packages that the setup installed will be hard.
