### ISSUE TITLE
Unable to run WM

### ISSUE THREAD

**Issue by 0xff001** [Axarva/dotfiles-2.0#101]
I followed savvyniks tutorial on how to install the WM, but it didnt work:

**Expected behavior**
I get an error could not resolve keysym XF86Audio

**Screenshots**
![image](https://user-images.githubusercontent.com/63504887/132114163-1de1e220-25c4-45cb-bd16-5036ed30cafb.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (Virtual Box VM)

**Additional context**
I am an extreme arch newbie, pretty much my third day of arch, so forgive me if im dumb

**Comment by Axarva** [comment]
Are you sure your .xinitrc is okay? 

Did you try xmonad - -recompile?

Last but not the least, did you try reinstalling xorg?

**Comment by 0xff001** [comment]
my xinitrc file is empty, xomand --recompile works with successs
reinstalling xorg gives the same error

**Comment by Axarva** [comment]
Then put in this line:
exec xmonad 

In your ~/.xinitrc and try running startx again.

**Comment by 0xff001** [comment]
added the line, same error

**Comment by Axarva** [comment]
Hm, are you sure the path of the file is correct? Just for a double check, what is the output of:
cat ~/.xinitrc

**Comment by Axarva** [comment]
Check out #75 and #78 too

**Comment by 0xff001** [comment]
i did the cat command, it says no such file or directory

**Comment by Axarva** [comment]
Okay.
Copy and paste this command.

mv ~/xinitrc ~/.xinitrc

**Comment by Axarva** [comment]
Then try the cat command again

Next, try startx.

**Comment by 0xff001** [comment]
running the command gives the error 

mv cannot stat '/home/ox_admin/xinitrc' : no such file or directory

**Comment by Axarva** [comment]
Okay.

echo “exec xmonad” > ~/.xinitrc

**Comment by 0xff001** [comment]
the command gives no output

**Comment by Axarva** [comment]
Try running startx now.

**Comment by 0xff001** [comment]
seems to have done something, its a black screen now

**Comment by 0xff001** [comment]
oh it worked

**Comment by 0xff001** [comment]
thanks!

**Comment by Axarva** [comment]
Great! The issue was your ~/.xinitrc file wasn’t where it was supposed to be. Will be closing now.

**Comment by 0xff001** [comment]
instead of the icons there are just black rectangles, what do i do about those?

**Comment by 0xff001** [comment]
oh shoot the issue is closed

**Comment by Axarva** [comment]
Could you send a screenshot?

**Comment by 0xff001** [comment]
![image](https://user-images.githubusercontent.com/63504887/132115218-199bef8c-74b1-416b-91a6-5bd61c3ad266.png)

**Comment by 0xff001** [comment]
i also cant open the terminal with the shortcut

**Comment by Axarva** [comment]
Did you follow the instructions in the VM folder?

**Comment by 0xff001** [comment]
no

**Comment by 0xff001** [comment]
i forgot about that

**Comment by Axarva** [comment]
There you go. 
Switch to a console, go to where you cloned this repo.

Then:
cp ./VM/picom.conf ~/.config/picom.conf

**Comment by 0xff001** [comment]
how do i switch to console?

**Comment by Axarva** [comment]
Next, open your ~/.xmonad/xmonad.hs in a text editor.

Search for the line `spawnOnce “picom —experimental-backends`.

Change the line to `spawnOnce “picom” `

**Comment by Axarva** [comment]
> how do i switch to console?

Try Alt+Ctrl+F2

Otherwise reboot, log in as root, and make the necessary changes.

**Comment by 0xff001** [comment]
it works! thanks again

**Comment by Axarva** [comment]
Great!
