### ISSUE TITLE
Wallpaper resets when boot. Arch Linux

### ISSUE THREAD

**Issue by rafaVls** [Axarva/dotfiles-2.0#102]
Hi! 

Is there anything on this setup that sets the wallpaper on boot? I have set wallpapers for my monitors using `feh`, and also execute `~/.fehbg` through `.xinitrc`, but the wallpapers still reset to the default `yosemite-lowpoly.jpg`.

~/.fehbg:
```bash
#!/bin/sh
feh --no-fehbg --bg-scale '/home/user/wallpapers/my-wallpaper-1.jpg' '/home/user/wallpapers/my-wallpaper-2.jpg'
```

~/.xinitrc:
```
exec xmonad
xmodmap ~/.Xmodmap &
~/.fehbg &
```

Is there anything I can do to make my wallpaper changes permanent?

**Comment by Axarva** [comment]
Yes, remove the line starting with:
spawnOnce “feh

From ~/.xmonad/xmonad.hs

(Sorry I’m on my phone, cannot type down the entire line, I hope this is heplful.)

**Comment by rafaVls** [comment]
I commented that line out, but my wallpapers just stayed black. I guess I was doing something wrong with my `.xinitrc`.

I ended up just chaning line 340 of `~/.xmonad/xmonad.hs` to my wallpapers, and that worked. Thank you!
