### ISSUE TITLE
Issue with betterlockscreen

### ISSUE THREAD

**Issue by blackbirdsr71** [Axarva/dotfiles-2.0#104]
Hi to all! I'm using this awesome Axarva's configuration since some weeks ago. But for a strange reason since a few days ago after upgrading arch y got some issues. Rofi, for example messed up text in the launcher. I managed to fix it by downgrading to 1.6 version. But I am now experiencing a strange behavior using betterlockscreen. After upgrading archlinux some days ago, after locking the screen i don't get any cached image but a blank screen and bellow the text it appears the language of my country (spanish). I don´t know where this comes from. I can't provide a decent screen print so i uploaded a image taken with my cellphone. 
![Betterlockscreen_image_20210908](https://user-images.githubusercontent.com/10891113/132540415-4cda2138-39cc-45ed-b935-95f33c91702f.jpeg)
Any ideas what's happening? Thank you in advance!

**Comment by Axarva** [comment]
I’m not sure… I don’t use betterlockscreen at all, I replaced it with light-locker quite a while ago. Maybe asking in the betterlockscreen repo will help?

**Comment by blackbirdsr71** [comment]
Hi!, Since when?, because i installed your dotfiles on archlinux fresh install and i got betterlockscreen. How do i apdate without breaking things?

**Comment by Spaxly** [comment]
Clone the repository and run the install script.

**Comment by Axarva** [comment]
Rofi configs are still stale, but I believe betterlockscreen can be fixed by re-caching the image and locking the screen. As for the language.. I'm not quite sure about this one since I don't use it anymore. I believe asking in the betterlockscreen repo would be more helpful than me :)
As for now, I'll close this issue.
