### ISSUE TITLE
Change xmonad installation

### ISSUE THREAD

**Issue by Kellegram** [Axarva/dotfiles-2.0#105]
It is better to grab xmonad-git and xmonad-contrib-git from AUR instead of using the non-git versions or the pacman version. 

I recommend grabbing: ``xmonad-git xmonad-contrib-git xmonad-recompile-pacman-hook-git`` from the AUR. the pacman hook will prevent a black screen on boot which can happen sometimes. The only way to fix it is to go to a TTY and recompile xmonad. That issue is common enough to be of concern. There is also a non-pacman hook, dunno if it's better. The git version of xmonad and contrib have fixes significantly faster than the main repo ones. They fix an issue with flameshot for example, one of them anyway.

**Comment by Kellegram** [comment]
I understand being hesitant to use the git version though coz breaking changes may arrive, but your xmonad setup is super minimal so unlikely. I had one breaking change in mine and I have a 600 line config, the change was described in their breaking changes doc anyway.

**Comment by Kellegram** [comment]
Another discovery when using everything bleeding edge: I get less issues in games when running fullscreen. Before I had trouble with games turning black permanently if I left the game window and stuff.

**Comment by d2rgaming-9000** [comment]
@Kellegram I've successfully installed the `git`'s version of the three packages, of xmonad, and I still see a black screen when I type startx...

**Comment by Kellegram** [comment]
@d2rgaming-9000 the git versions are NOT in pacman repos. They are in the AUR. For those you need an AUR helper like paru. AUR is a user repository.

**Comment by d2rgaming-9000** [comment]
I would assume the installer script creates it automatically.

In any case, if it is irrelevant, then what would be causing that phenomenon. Pretty sure I did everything right this time around. I've installed the `git`'s version of the packages, and what's not.. (I would normally assume, after the introduction of the new packages, to recompile xmonad so that it reconfigures correctly.).

**Comment by Kellegram** [comment]
@Axarva What I do now is install haskell stuff via stack. Arch repos suck for anything haskell, always behind in version and very unstable. Here is my [hand-written script](https://gitlab.com/kellegram/kellmonad/-/blob/master/install_xmonad_with_stack.sh) to install xmonad and xmonad-contrib with stack. I also written sed commands to work around a completely random and inconsistent bug where it fails to install because something in config changes to what it shouldn't. The only issue is the path might not be constant but that's easy to fix I think, will do so later. The script works tho and that way haskell stuff is detached from the native package management. 

As for ewmh support etc. I spent months researching and testing and am pretty confident that (at least at the time of last update) I have the most modern xmonad config out there. Most of the ones online do it wrong or are severely outdated. I moved to gitlab for now, so here is the [current config](https://gitlab.com/kellegram/my-dotfiles/-/blob/master/.xmonad/xmonad.hs), I haven't used linux for a while due to work and stuff.

**Comment by Axarva** [comment]
Turns out the functions you used in your config are only available for xmonad-contrib-0.17.0, while the version available on most distros is 0.16. We *could* make everything installed by stack, but I'm not quite sure how to test it out.

**Comment by Kellegram** [comment]
> Turns out the functions you used in your config are only available for xmonad-contrib-0.17.0, while the version available on most distros is 0.16. We _could_ make everything installed by stack, but I'm not quite sure how to test it out.

Yes that's what I am saying, it's better to just use stack, the packaging is not good. My script installs everything.
