### ISSUE TITLE
rofi menu not displaying text of applications

### ISSUE THREAD

**Issue by rafaVls** [Axarva/dotfiles-2.0#109]
**Describe the bug**
The rofi menu (activated with `Super + O`) doesn't show the name of the applications, only their icons.

**To Reproduce**
1. Hit the `Super + O` keybind.
2. See error

**Expected behavior**
I expect to see the name of the application next to the icon.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Kernel: 5.14.8-arch1-1

**Additional context**
I know that when I first installed the configs from this repo, the text was there. I couldn't tell you when it stopped working, it's been a while.

I would take a screenshot, but `flameshot` doesn't work properly while the rofi menu is active.

**Comment by Axarva** [comment]
Are you sure this isn’t because rofi got updated?

**Comment by Axarva** [comment]
I believe version 1.5.4 was the one supported. Possibly some configs changed, and these don’t work. I suggest trying to get them up to date or using an older version of rofi.

**Comment by Axarva** [comment]
Rofi configs have been updated for version 1.7.0, which is the latest stable. I believe this should be closed now. Thanks!
