### ISSUE TITLE
Installation conflict of two different xmonad versions.

### ISSUE THREAD

**Issue by d2rgaming-9000** [Axarva/dotfiles-2.0#110]
Hi I had already installed another xmonad automated script that configured a lot of stuff. I can link the source that I installed it from if that would be relevant or helpful. The intention was to test different custom xmonad's.

I installed Axarva's/dotfiles xmonad [afterwards and prior] via the provided guide on the site, both prior and after I had post-installed the other xmonad script in question. And whenever I try to login to axarva's /dotfiles version of xmonad, it would log me in to the other xmonad environment in question. And not axarva's /dotfiles version of xmonad.

I wish there was a way to log in to axarva's /dotfiles version of xmonad, and / or remove the other xmonad in question. 

I was thinking about removing or reconfiguring xmonad's conf folder to apply changes. (Not sure if that is going to work), but I will try and see if that fixes and report back.

EDIT:
I'm also using gnome environment. I think it also interferes with `xmoand`'s `better lock-screen`. Because I only see gnome's login screen.

Thank you.

-D2

**Comment by Axarva** [comment]
The bottom dock is only populated once you configure it by yourself. I’m not quite sure about what else can I help with

**Comment by d2rgaming-9000** [comment]
@Axarva Is there anyway to increase the icon size and how do I go on about configuring the dock so that its populated with stuff. :)

**Comment by d2rgaming-9000** [comment]
@Axarva I'm getting some weird interaction. When I hit `Super + P` twice to dismiss the drop down options window, it does not disappear. And neither does `esc` key dismisses it. That goes for `Super + s` as well. But the `esc` /does/ dismiss the search menu key for `Super + o`. I'm wondering what keys I'm missing xd.

**Comment by d2rgaming-9000** [comment]
Original issue; fixed.
