### ISSUE TITLE
Tint2 Icons not Displaying properly on the left top bar

### ISSUE THREAD

**Issue by Marcus-Arcadius** [Axarva/dotfiles-2.0#113]
![image](https://user-images.githubusercontent.com/78793842/138555358-659945de-fb49-4716-90a5-03ed2f6f16ab.png)

**Comment by Axarva** [comment]
What resolution are you running this bar on? Shortening the bar should help.

**Comment by Marcus-Arcadius** [comment]
> What resolution are you running this bar on? Shortening the bar should help.

2560x1440
