### ISSUE TITLE
could not load module xmonad

### ISSUE THREAD

**Issue by SadPersonn** [Axarva/dotfiles-2.0#114]
PLEASE MAKE .xinitrc TO LAUNCH, or just use your Display Manager (ie. lightdm or sddm, etc.)
For startpage, copy the startpage directory into wherever you want, and set it as new tab in firefox settings.
For more info on startpage (Which is a fork of Prismatic Night), visit https://github.com/dbuxy218/Prismatic-Night#Firefoxtheme
ALL DONE! Reboot for all changes to take place!
Open issues on github or ask me on discord or whatever if you face issues.
Install Museo Sans as well. Frome Adobe I believe.
If the bar doesn't work, use tint2conf and set stuff up, if you're hopelessly lost, open an issue.
These instructions have been saved to ~/Note.txt. Make sure to go through them.
For instructions regarding usage on VirtualMachines, please refer to the VM folder of the repo.
XMonad will use ghc to recompile, because "/home/sadperson/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/sadperson/.xmonad/xmonad.hs

xmonad.hs:9:1: error:
    Could not load module `XMonad'
    It is a member of the package `xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 data-default-0.7.1.1-8aGzV3AyDr077p6b91gXPe utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
9 | import XMonad
  | ^^^^^^^^^^^^^

xmonad.hs:10:1: error:
    Could not load module `XMonad.Layout.Fullscreen'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
10 | import XMonad.Layout.Fullscreen
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

xmonad.hs:14:1: error:
    Could not load module `XMonad.Util.SpawnOnce'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
14 | import XMonad.Util.SpawnOnce ( spawnOnce )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

xmonad.hs:15:1: error:
    Could not load module `Graphics.X11.ExtraTypes.XF86'
    It is a member of the package `X11-1.10.1-KOexKqfvsIxF1vDZupKBH4'
    which is unusable due to missing dependencies:
      data-default-class-0.1.2.0-LBmwYNzg9cwLSaLiX5AQfC
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
15 | import Graphics.X11.ExtraTypes.XF86 (xF86XK_AudioLowerVolume, xF86XK_AudioRaiseVolume, xF86XK_AudioMute, xF86XK_MonBrightnessDown, xF86XK_MonBrightnessUp, xF86XK_AudioPlay, xF86XK_AudioPrev, xF86XK_AudioNext)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

xmonad.hs:16:1: error:
    Could not load module `XMonad.Hooks.EwmhDesktops'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
16 | import XMonad.Hooks.EwmhDesktops ( ewmh )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

xmonad.hs:18:1: error:
    Could not load module `XMonad.Layout.NoBorders'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import XMonad.Layout.NoBorders
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

xmonad.hs:19:1: error:
    Could not load module `XMonad.Hooks.ManageDocks'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import XMonad.Hooks.ManageDocks
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

xmonad.hs:21:1: error:
    Could not load module `XMonad.Hooks.ManageHelpers'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
21 | import XMonad.Hooks.ManageHelpers ( doFullFloat, isFullscreen )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

xmonad.hs:22:1: error:
    Could not load module `XMonad.Layout.Spacing'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
22 | import XMonad.Layout.Spacing ( spacingRaw, Border(Border) )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

xmonad.hs:23:1: error:
    Could not load module `XMonad.Layout.Gaps'
    It is a member of the package `xmonad-contrib-0.16-DWofk4iSjDEEgk0jv09cAG'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 X11-xft-0.3.1-JEfIMbOM9hM4IVCmV6QHwt old-locale-1.0.0.7-8b6vATcbl2rGNT5WzdAV1N old-time-1.1.0.3-K1bOYVfsfw9D9troqm7gA3 random-1.2.1-GTaXQEmVKZP2pnqal7ZY4e utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
23 | import XMonad.Layout.Gaps
   | ^^^^^^^^^^^^^^^^^^^^^^^^^...

xmonad.hs:29:1: error:
    Could not load module `XMonad.StackSet'
    It is a member of the package `xmonad-0.15-7dMeNFbP8IeE3YLbUIFRoc'
    which is unusable due to missing dependencies:
      X11-1.10.1-KOexKqfvsIxF1vDZupKBH4 data-default-0.7.1.1-8aGzV3AyDr077p6b91gXPe utf8-string-1.0.2-FSV4F6pxd5y7PjtRkbEpDf
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
29 | import qualified XMonad.StackSet as W
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Please check the file for errors.

Warning: locale not supported by C library, locale unchanged

i use arch linux

**Comment by Axarva** [comment]
Looks like a missing-dependency case. I say you install all the missing dependencies (I'm not sure why your package manager didn't do it) and try again.
Also, this isn't strictly an issue of this repo, and the issue is stale. I'll be closing this.
