### ISSUE TITLE
How to disable the health notifications.

### ISSUE THREAD

**Issue by dragonfetus** [Axarva/dotfiles-2.0#115]
As the title says I want to disable the health notifications as they are a little too frequent.

**Comment by dragonfetus** [comment]
does anyone has a solution ?

**Comment by Axarva** [comment]
Sorry I’ve been quite busy. If you want to remove them entirely, look into ~/bin where two scripts: notieye and notipose are present. Delete the scripts, or just comment out their contents.

**Comment by dragonfetus** [comment]
Thank you very much.
