### ISSUE TITLE
Firefox smooth edges

### ISSUE THREAD

**Issue by barry271828-e** [Axarva/dotfiles-2.0#116]
Firefox:
![2021-11-09_09-27-00](https://user-images.githubusercontent.com/82360052/140844945-85f735e1-e01b-4ab5-86f1-45e6dd85485b.png)
Chrome:
![2021-11-09_09-28-58](https://user-images.githubusercontent.com/82360052/140845050-b68724ca-407a-4706-9291-09e69cc27f05.png)

Any fix for that?

**Comment by Axarva** [comment]
That's odd, check picom.conf.

**Comment by barry271828-e** [comment]
It's fine, already fixed.
Just install the binary version of Firefox.
