### ISSUE TITLE
Covert EWW XML to YUCK

### ISSUE THREAD

**Issue by dmadisetti** [Axarva/dotfiles-2.0#118]
I think EWW has dropped xml totally? I saw you (@Axarva) made contributions to the converter: https://github.com/undefinedDarkness/ewwxml 
I tried running it on your configs to mild success, and wondered if you'd looked into it yourself at all.

**Comment by Axarva** [comment]
Like you said, there will be a few minor issues with the setup. I'll start working to fix them quite soon, then it will be up on the repo. Thanks for pointing this out again!

**Comment by Axarva** [comment]
Yuck is live on the modified branch! I'd love it if a few users could test it out.

**Comment by Axarva** [comment]
Migrated main branch to yuck with 2df67e4
