### ISSUE TITLE
Wierd looking dashboard

### ISSUE THREAD

**Issue by arnav7633** [Axarva/dotfiles-2.0#119]
![image](https://user-images.githubusercontent.com/68459855/146582434-71aaadda-1744-4d51-8765-53f8e9c268b4.png)
Hey i have such a dashboard and none of the buttons works.
I setup cron job for weather and quotes but the alignment is crooked

**Comment by Axarva** [comment]
If you were to remove the Screenshot file and the `BlueSky` file/directory from your home and put them somewhere else, this issue should resolve itself.

**Comment by Axarva** [comment]
Fixed in a47a799
