### ISSUE TITLE
Can you help me? I am new at linux.

### ISSUE THREAD

**Issue by kaldera3451** [Axarva/dotfiles-2.0#12]
I use a arch. Nothing is installed except Xmonad. I'm typing Kontrab -e into the terminal and it says "contrab: command not found". Can you help me, how can I set up your configuration?

**Comment by aleemont** [comment]
`sudo pacman -S crontab`
(Don't mispell it it's "cRontab")

`EDITOR=nano crontab -e`

If you are very new to linux and you can't even configure your crontab you shouldn't have started using Arch with xmonad tho. 
Try with some easier DE and WM. Arch is for more experienced people.

**Comment by kaldera3451** [comment]
sorry this is Google translation's fault.

**Comment by kaldera3451** [comment]
error: target not found: crontab

**Comment by kaldera3451** [comment]
pacman does not working

**Comment by Axarva** [comment]
@kaldera3451 Did you get cron installed?
The command actually is `sudo pacman -S cronie`.

**Comment by kaldera3451** [comment]
I figured out but some widgets are missing.  logout & shutdown icons not working.  Rofi launcher error. 1 tick lag on menus. that`s are my problem sorry for bad english.

**Comment by kaldera3451** [comment]
I can use the system like this thanks for sharing this
