### ISSUE TITLE
Getweather script not working

### ISSUE THREAD

**Issue by Takusan1** [Axarva/dotfiles-2.0#120]

**Comment by Takusan1** [comment]
I've setup crontab to contain the script, added a working API, ID, and Units to the script as well. Quotes are also not working, so I'm not sure if I've messed something up there. I thought maybe the issue might be that eww.yuck doesn't exist, and I'm instead using eww.xml.

**Comment by Takusan1** [comment]
![Screenshot_2021-12-30_02-06-44](https://user-images.githubusercontent.com/96730574/147623682-6a03d237-4a96-4c2a-bb5e-3f27a8754c3e.png)
Here's how its looking.

**Comment by Axarva** [comment]
Did you try running the getweather and quotes scripts manually? What errors do they give?

**Comment by Axarva** [comment]
Stale issue. Closing for now. Please recomment to get the issue open again.
