### ISSUE TITLE
Tint2 bars overlapping

### ISSUE THREAD

**Issue by sfulham** [Axarva/dotfiles-2.0#123]
**Describe the bug**
Tint2 top right corner bars aren't displaying correctly, they are overlapping.

**To Reproduce**
1. Use a fresh install of arch, and run the install script.

**Expected behavior**
The bars would be in the correct positions

**Screenshots**
![image](https://user-images.githubusercontent.com/40906364/150462377-4682e158-44f2-40c0-bd64-84903cd02f9b.png)

**Desktop (please complete the following information):**
 - OS: Arch
 - Screen Resolution: 1920x1080

**Comment by Axarva** [comment]
This is because of scaling issues. I believe using `tint2conf` to edit the length and positions of bars will be helpful here. I know it's a hassle, but I'll get to work on this.
