### ISSUE TITLE
Cant open side bar or dashboard

### ISSUE THREAD

**Issue by PipeVerri** [Axarva/dotfiles-2.0#124]
Hello, i just installed this on manjaro, i followed all the install steps and verified that the dependencies where installed. everything seems to work fine except for the sidebar and dashboard, all the shortcuts work except win + P or win + S, nothing appears, what did i do wrong?

**Comment by Axarva** [comment]
Hello
Did you try running eww manually?
What does the output of “eww logs” say?

**Comment by PipeVerri** [comment]
eww logs doesnt show anything, and the bin folder is in my path
but when i run eww reload, i get this:
`error: Wrong type of expression
    ┌─ /home/pipev/.config/eww/eww.yuck:236:8
    │
236 │                 :geometry (geometry :x "505px" :y "100px" :width "690px" :height "100px")
    │                 ───────── Expected a `List` here
    │
    → Expected: List
           Got: Keyword
`

**Comment by PipeVerri** [comment]
I think i got near the solution.
i ran this, the command that xmonad runs when it opens the dashboard: `exec ~/bin/eww open-many blur_full weather profile quote search_full incognito-icon vpn-icon home_dir screenshot power_full reboot_full lock_full logout_full suspend_full`

My terminal crashed everytime i did that, so i redirected the errors to a file and this is what i got:

`failed to open window `blur_full`

Caused by:
    No window named 'blur_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `weather`

Caused by:
    No window named 'weather' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `profile`

Caused by:
    No window named 'profile' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `quote`

Caused by:
    No window named 'quote' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `search_full`

Caused by:
    No window named 'search_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `incognito-icon`

Caused by:
    No window named 'incognito-icon' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `vpn-icon`

Caused by:
    No window named 'vpn-icon' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `home_dir`

Caused by:
    No window named 'home_dir' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `screenshot`

Caused by:
    No window named 'screenshot' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `power_full`

Caused by:
    No window named 'power_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `reboot_full`

Caused by:
    No window named 'reboot_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `lock_full`

Caused by:
    No window named 'lock_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `logout_full`

Caused by:
    No window named 'logout_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
failed to open window `suspend_full`

Caused by:
    No window named 'suspend_full' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.`

**Comment by PipeVerri** [comment]
By the way, heres my eww config file
[eww_config.txt](https://github.com/Axarva/dotfiles-2.0/files/7954390/eww_config.txt)

**Comment by PipeVerri** [comment]
I have found and fixed the issue.
The file for eww 1336 works without issue, there is a difference in the ;; on the line 236 of the files, changed line 236 of eww 1920 to line 236 of eww 1336 and it works

**Comment by Eason0210** [comment]
Have the same issue. 

@Axarva  Please fix this typo 
https://github.com/Axarva/dotfiles-2.0/blob/e7e8f938c50e646907e870a122c3ee81307aea4d/config/eww-1920/eww.yuck#L236

**Comment by Axarva** [comment]
Fixed in main through PR and manually in modified through 8cc118. Thank you!
