### ISSUE TITLE
Unaligned music widget

### ISSUE THREAD

**Issue by PipeVerri** [Axarva/dotfiles-2.0#126]
Hello! i currently have 2 problems:

1) The music widget is a little bit down so it overlaps
2) When there's music playing, it expands a little bit to the right

What values should i edit in the eww.scss/eww.yuck to fix that?

Here's a screenshot of it
![image](https://user-images.githubusercontent.com/47497965/151673488-3148c090-1d35-48ed-9089-b1713afb3736.png)

**Comment by PipeVerri** [comment]
Heres a screenshot of it
![image](https://user-images.githubusercontent.com/47497965/151673523-daecabb3-9b3f-45e7-9b77-dc82cee06dc7.png)

**Comment by Axarva** [comment]
This should be fixed in 645d003. Could you test it out?

**Comment by PipeVerri** [comment]
Now it works, thanks!
