### ISSUE TITLE
Widgets not showing on fresh Archinstall

### ISSUE THREAD

**Issue by NorViking** [Axarva/dotfiles-2.0#127]
HI!
The widgets are not showing at all with the keybinding win + p / win + s.
Steps taken:
Fresh install of arch using arch install script (pacman -S archinstall).
Add export PATH="$PATH:$HOME/bin" to your ~/.bashrc.
Populated .xinitrc with "exec xmonad".
Populated .bash_profile with "startx".
Downloaded and installed Museo Sans 300 to /.local/share/fonts (fc-cache -f).
Manually compiled eww and moved it to /home/$USER/bin.

Host info:
OS: Arch Linux x86_64
Host: Lenovo T490
Kernel: 5.16.2
Shell: bash 5.1.16
Resolution: 1920x1080
VM: xmonad
Theme: Adwaita GTK2/3
Icons: candy-icons
Terminal: alacritty
Termianl Font: Source Cod
CPU: Intel i7
GPU: Intel WhiskeyLake UHD Graphics

**Comment by PipeVerri** [comment]
is /home/{your_user}/bin in your path? (get your path by running `echo $PATH`)

**Comment by NorViking** [comment]
Thanks for the reply and yeah, you are right! PATH was misconfigured. I got the widgets working now, but the the icons in xmobar isn't responding when clicked. Trying to open network manager but nothing is happening.

**Comment by d2rgaming-9000** [comment]
I still don't understand why the xmonad environment does not load for me and on many several occasions I've tried fresh install with arch and it still would not start no matter what. This is following savvy's YouTube video tutorial.

**Comment by Axarva** [comment]
Hey there, is everyone still having trouble or is everything resolved?

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened. Thank you!
