### ISSUE TITLE
hmm i don't think it should look like this

### ISSUE THREAD

**Issue by zombiezooz25** [Axarva/dotfiles-2.0#129]
![??](https://user-images.githubusercontent.com/99162118/155043453-e5bdfcbe-89a6-416e-b4a8-c858e92e9d94.png)

**Comment by Axarva** [comment]
Make sure picom is working, then do the weather stuff, then make sure you have the correct nerd font. That should fix up a lot of these problems.

**Comment by Axarva** [comment]
Any updates?

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened.
