### ISSUE TITLE
Using second monitor

### ISSUE THREAD

**Issue by Alonely0** [Axarva/dotfiles-2.0#13]
I'm new in xmonad.
I applied your config, and now I don't see anything in my second display. When I log in with KDE Plasma, all works well. I have an NVIDIA card, specifically a 1650.

**Comment by Axarva** [comment]
What exactly was the process you followed? I’ve had a person install it on a setup with dual monitors install it and they showed me it worked fine, although the process was quite long.

**Comment by Alonely0** [comment]
I executed the installation script. I didn't have xmonad installed already

**Comment by Axarva** [comment]
The installation script as in the one for Arch Linux? Or the other one? If it were for Arch, could you retry this command just in case something failed to install?
`yay -S  picom-jonaburg-git tint2 acpi rofi-git candy-icons wmctrl alacritty playerctl dunst xmonad-contrib jq xclip maim`
No harm in doing it again even if it succeded

**Comment by Alonely0** [comment]
I had to search through forums and edit a little of the config, but works better now (isn't perfect)
