### ISSUE TITLE
the weather is not working

### ISSUE THREAD

**Issue by alavaelian** [Axarva/dotfiles-2.0#130]
i already did the weather file config and it still not working, other issue is that some programs with floating windows like gimp or kdenlive do not set to floating automatically

**Comment by PipeVerri** [comment]
Try running the script manually? are there any permission denied messages? if you run it manually weather is displayed correctly?

**Comment by alavaelian** [comment]
thans mate for answer and if i exec it manually its work, but it still cannot  see the memory usage, the little mensaje in the dashboard and the image;

**Comment by DivaySaini** [comment]
it's been months, got any solution?

**Comment by Axarva** [comment]
As a general rule of thumb when working with the weather script, please check all your credentials in the script are fine. Then check if the script runs in the terminal without errors and produces the desired output (which is a change in the weather widget).
If it does, then proceed to check your cron configuration.

If all of them seem to be correct and the script still doesn't work, please do recomment and I'll be happy to reopen this issue.
