### ISSUE TITLE
Installed over xfce4 Garuda

### ISSUE THREAD

**Issue by U-n-Own** [Axarva/dotfiles-2.0#131]
Hi, i want to clarify that i followed all the steps, and checked if i did some mistakes before opening this
So, i tried to run the script on my distirbution of arch, i had Garuda with xfce4 and when i installed this all went pretty linearly, but when i restarted my pc the Display Manager wasn't shown and i had a mix between the xmonad and old Desktop environment, then i went into the tty2 and after log in with usr and pw the Windows manager was back, then every time i had to restart i had to enter in tty2 then log in and enter.
What happened?
I tried to install a new display manager (sddm), and now that is working.

Also when i open the terminal this message is being show

`xauth: (stdin):2:  unknown command "85f45bad7c45606e9e1492d8c65125bf"
xauth: (stdin):2:  unknown command "85f45bad7c45606e9e1492d8c65125bf"

/usr/lib/Xorg.wrap: Only console users are allowed to run the X server
^Cxinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: unexpected signal 2
Couldn't get a file descriptor referring to the console.`

**Comment by Axarva** [comment]
I'm really not sure what is going on here. Most display managers should just allow you to switch between DEs and WMs.

**Comment by Axarva** [comment]
As for `/usr/lib/Xorg.wrap: Only console users are allowed to run the X server`, you should follow this:
![image](https://user-images.githubusercontent.com/66304313/156891811-f3b8bbc4-b166-44f3-8b0a-9e9425df1c32.png)

[Source](https://unix.stackexchange.com/questions/478742/error-when-trying-to-use-xorg-only-console-users-are-allowed-to-run-the-x-serve)

**Comment by U-n-Own** [comment]
i dont' have that config file also i can't create because it's a readonly

**Comment by Axarva** [comment]
You’ll need superuser access.

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened.
