### ISSUE TITLE
Cant install Paru

### ISSUE THREAD

**Issue by Rudasyy579** [Axarva/dotfiles-2.0#133]
Installing Paru dosent work as it doesnt  allow using makepkg with root 
im on a vm
![Capture](https://user-images.githubusercontent.com/89593717/160241830-246f55ac-c057-4421-9d54-314be2237792.PNG)

**Comment by Axarva** [comment]
Try running the script as a normal user instead. It seems you are logged in as root.

**Comment by Rudasyy579** [comment]
i had use the nobody user and give it alot of perms
