### ISSUE TITLE
How to change icons used in this workspace?

### ISSUE THREAD

**Issue by DPatel0211** [Axarva/dotfiles-2.0#134]
Where can I find the configuration file for this workspace to edit these icons or is there an option to do this with the configuration settings GUI? I use Brave and Soundcloud mainly so I want to edit the Firefox/Spotify icons out.
![image](https://user-images.githubusercontent.com/43239911/160261449-585f97ca-7308-447d-9c34-3da2f3dc6ca7.png)

**Comment by Axarva** [comment]
Try running the command “tint2conf” (without the quotes, of course) in your terminal.

**Comment by DPatel0211** [comment]
Where do I scroll down to in the workspace config?

**Comment by redgloboli** [comment]
look at xmonad.hs and find a line similar to this one:

myWorkspaces    = ["\63083", "\63288", "\63306", "\61723", "\63107", "\63601", "\62886", "\61713", "\61884"]

These numbers are the workspace names and also the icons.
