### ISSUE TITLE
missing widgets

### ISSUE THREAD

**Issue by s7evo7one** [Axarva/dotfiles-2.0#137]
hey awesome job :) iv ran into a couple of problems ive been at it for weeks with no luck any help would be much appreciated :)
![2022-04-03_00-52-48](https://user-images.githubusercontent.com/93963262/161405562-97004f52-8c72-447d-97b0-2f4950f63980.png)
)

**Comment by redgloboli** [comment]
missing widget is the do-not-disturb function.

https://github.com/Axarva/dotfiles-2.0/issues/135

**Comment by s7evo7one** [comment]
thanks for pointing that out bro......... but do u av a fix

**Comment by Axarva** [comment]
The missing widget has been fixed in the recent PR by @redgloboli (Thank you!), I'm not sure how you have a temperature of 273 degrees, and refreshing the widget screen would probably fix the missing quotes. Good luck!

**Comment by s7evo7one** [comment]
thanks for the help got missing widget working kinda :) thanks for pointing out temp will try n fix it , im new to linux still finding my way about things :)

**Comment by Axarva** [comment]
Any updates?

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened.
