### ISSUE TITLE
How do I restrict my picom configuration file from removing rounded borders from a specific tint2rc configuration file running on tint2?

### ISSUE THREAD

**Issue by DPatel0211** [Axarva/dotfiles-2.0#138]
![image](https://user-images.githubusercontent.com/43239911/161852648-3e37b779-cb8b-4d58-a8ea-22b00f55be39.png)
I want this specific tint2 config to have its rounded borders while the launcher, the wifi/battery/inhibitor, and time tint2 configs have their borders removed. Is this possible through edited the picom config file?

**Comment by Axarva** [comment]
I'm not sure what you mean, if you wish to remove round corners from specific bars in tint2, you should target those and set specific rules in your picom configuration.
