### ISSUE TITLE
Missing widgets and images

### ISSUE THREAD

**Issue by MitasTech** [Axarva/dotfiles-2.0#139]
![Screenshot_20220412_124815](https://user-images.githubusercontent.com/77465022/162933238-ffa0f1e1-19bc-44b8-b37a-bb14ac63c6e1.png)

![Screenshot_20220412_124847](https://user-images.githubusercontent.com/77465022/162933276-7c0a50d9-9ae0-4201-a426-f60170f279a7.png)

**Comment by MitasTech** [comment]
i managed to "fix" the weather widget, turns out i was missing the preferred unit on the getweather script.
But still idk how to fix the profile image and the widget below on the first image

**Comment by coopikoop** [comment]
i have the exact same issue. both getweather and getquote scripts work when running them from the terminal

**Comment by Axarva** [comment]
Not sure why this would happen. Are you sure cron is running on your system?

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened.
