### ISSUE TITLE
how to pin apps , how to disable fix ur posture thing

### ISSUE THREAD

**Issue by Godskull** [Axarva/dotfiles-2.0#141]
![Screenshot_20220423_153628](https://user-images.githubusercontent.com/43469241/164890062-42ad10df-06af-4d68-b75e-9cd02f45d893.png)
how i add apps to this ?

and how i disable that fix posture ?

**Comment by MitasTech** [comment]
open terminal and type 'tint2conf' , select that bar and modify it

**Comment by Axarva** [comment]
Head to ~/bin and remove the notipose script. That will disable the posture messages. Good luck!
