### ISSUE TITLE
Audio control not working with bluetooth headset

### ISSUE THREAD

**Issue by DivaySaini** [Axarva/dotfiles-2.0#143]
Hello, the audio control is not working with bluetooth headset connected, i'm on arch linux. the volume icons doesn't work in xmonad (i get that) but the volume bar provided in the menu (super + s) is also not working (while headset is connected). it automatically picks up any volume level whenever i reboot (just reconnecting doesn't change anything). i'll provide more info if anyone will ask.
thank you
Divay

**Comment by Axarva** [comment]
I think the trouble here is with alsa, which is what I used to create the menus. Could you please look up if anyone has faced this same issue with alsa before?

**Comment by Axarva** [comment]
Stale issue. Please comment to get it reopened.
