### ISSUE TITLE
tint2 not working

### ISSUE THREAD

**Issue by PhoenixHeron1** [Axarva/dotfiles-2.0#145]
**tint2 does not starts on boot**
1. title
2. manually starting tint2 results in tint2 using default ugly themes

**Expected behavior**
It should use the custom theme and should run automatically on bootup

**Screenshots**
![image](https://user-images.githubusercontent.com/85755985/167350123-dfd7580f-627c-45f6-94b3-f29ac78ff321.png)
![image](https://user-images.githubusercontent.com/85755985/167350208-d06442ab-06ec-4ae5-b01a-3ac354281d5f.png)

**Desktop**
 - Arch Linux

**Comment by ArmoredVortex** [comment]
Mine wouldn't start on boot, nor manually
![image](https://user-images.githubusercontent.com/66690593/167904205-13f6eec0-4979-4d55-a1e8-1be51d529224.png)
Sorry if this isn't related.

**Comment by ArmoredVortex** [comment]
Update: Using the tint2 package from the AUR worked for me, just had to update the bartoggle to use the package.
Seems like the issue rests with the tint2 bin in the repo

**Comment by ArmoredVortex** [comment]
> > Update: Using the tint2 package from the AUR worked for me, just had to update the bartoggle to use the package. Seems like the issue rests with the tint2 bin in the repo
> 
> I have the same issue as the original post. What's the bar toggle you referring too?

The script inside the bin folder, `$HOME/bin/bartoggle`
Instead of using `$HOME/bin/tint2` inside the script, I replaced it with `/sbin/tint2`

**Comment by FeintDoxx** [comment]
> > > Update: Using the tint2 package from the AUR worked for me, just had to update the bartoggle to use the package. Seems like the issue rests with the tint2 bin in the repo
> > 
> > 
> > I have the same issue as the original post. What's the bar toggle you referring too?
> 
> The script inside the bin folder, `$HOME/bin/bartoggle` Instead of using `$HOME/bin/tint2` inside the script, I replaced it with `/sbin/tint2`

Yeah, this worked for me too.

**Comment by Axarva** [comment]
The problem is that your system doesn’t have libraries for tint2 to work. Installing through the AUR will add the required libraries and another binary of tint2. This is more of a hack than a fix since I’d rather suggest everyone to compile the binary through my fork and place it in their ~/bin. But if it works it works, I guess. I’ll make tint2 a requirement in the setup soon. Thanks!
