### ISSUE TITLE
Tint2 not working and latest xmonad update break systems

### ISSUE THREAD

**Issue by RajrupDasid** [Axarva/dotfiles-2.0#146]
**Describe the bug**
This problem is related to latest xmonad update , when you update to latest and reboot the spawn config file changes and booting into a black TTY environment , to get rid of this  we need to recompile it to work again
which is a bit odd and confusing a little for understand , not easily understandable the problem 
so need a quick fix for this.
And many days ago suddenly tint2 conf and all of the cool icons and dashboard and status page stopped working.
please update it with latest bugfix .

**xmonad-x86_64-linux,** this is the notorious file after the latest xmonad update which is reasonable for the problem this file hasn't have the old config call files  any more please fix it.

Thanks

**Comment by Axarva** [comment]
Will look into this.

**Comment by RajrupDasid** [comment]
HI sorry for the delay 
tint2 is working again
the full details is 

os = pure arch linux latest
kernel = latest
Window manager = Xmonad mod made by you= latest fetched yesterday 
issue--------------------------------------------
  every time  xmonad updates to latest version does not  trigger it to compile it again.
so that's why system breaks and comes with an error mentioned upper okay.
I have to manually re compile  it to work it again .
after updating to latest xmonad and xmonad contrib version after rebooting or even a cold boot cause it to break
when i log in to my system after weak up it throw up error message that something is not configure right way .
i will attach a photo next time when i face the issue again.
after issue come it wont startup the window manager cause manually recompile that arch.sh file inside dot file .

hope you understand the issue 
i will attach the picture next time.

i pulled the latest update yesterday and  an update came which cause that issue to triggered okay, after recompile manually 
I see that tint2 and icon works again.
Thanks for that I will attach the message here that you can understand it more clearly okay.
thanks

**Comment by RajrupDasid** [comment]
Today all of my system broke , because for a new xmonad update and i had to re install everything,
The problem i was mentioning 
pixman error- failed to enable io ports 0000-03ff


**xmonad error-
xmoand is recompiling and replacing it self with another xmonad process .
xmonad  will use ghc to recompile because .xmonad/build file doesnot exist ,
xmonad skipping the recompiling process because it is not forced , and neither xmonad .hs nor any .
error while shared libs :--- libHSxmonad-contrib......    cannot open shared object : no such file or directory** 



here xserver broke and i was ended up being a tty area
here i have to cd into dotfiles and there fore   compile stuffs again manually 
after the all installation process finish i can successfully login again with a working environment .
but today the recompile process broke because a file already linked in the system , so not gonna create link again as we know, 
so there for i install xfce environment there for download arch iso and there after i install your configs again to run successfully, the problem is that i lost many of my important files unfortunately

**Comment by Axarva** [comment]
This is confusing. I'll update the install script for that line now.

Side note: Arch is bleeding-edge. Breaking changes are to be expected. As much as I'd like to, I can't walk you through issues caused on an Arch system, partly because I don't use Arch, partly also because I have no clue how to fix them. If you'd like to keep running Arch, I suggest you be prepared for these issues. Half of them are because of the packages you update rather than this repository. I'll be closing this for now.

**Comment by RajrupDasid** [comment]
yeah no issue . I will maintain my system. Sorry but can't stop using or loving Arch
