### ISSUE TITLE
Disabling Xmonad Alert Sound

### ISSUE THREAD

**Issue by silvolde428** [Axarva/dotfiles-2.0#149]
Anyone know how to turn off the alert sound that plays when you edit the taskbar and other widgets?

Also to turn off screen lock or delay it for longer

Any help is most appreciated :)

**Comment by Axarva** [comment]
I’m not sure which alert sound you mean.

**Comment by silvolde428** [comment]
In the app that I forget the name of, to change the layout/appearance of widgets, there is a high pitched noise that plays every time I make a change. This is after I get the sidebars and things to show up.

**Comment by Axarva** [comment]
What happens if you `rm ~/bin/Low-battery-sound.mp3`? Does that solve the issue?

**Comment by silvolde428** [comment]
I would think so. I don't have your rice installed now though, so I can't actually check

**Comment by Axarva** [comment]
Alright. Since no one else has been reporting this, I'll be closing this for now.
