### ISSUE TITLE
libasan.so.6 error in arch linux (tint2)

### ISSUE THREAD

**Issue by emelcd** [Axarva/dotfiles-2.0#153]
**Describe the bug**
The script is pointing to libasan.so.6 while the has libasan.so.8. This causes tint2 not working properly. 

`error while loading shared libraries: libasan.so.6: cannot open shared object file: No such file or directory`

**Workaround**
Manage to fixed by creating a symbolic link to libasan.so.8 and fooling tint2

```sh
sudo ln -s /usr/lib/libasan.so.8 /usr/lib/libasan.so.6
```

**To Reproduce**
1. Try yo launch `bartoggle` hook.
2. Get the error described

**Expected behavior**
Work as normal

**Desktop (please complete the followin information):**
 - OS: installed on Arch Linux using  `install-on-arch.sh`

**Additional context**

**Comment by Axarva** [comment]
Put in the fix in the install script for now.
