### ISSUE TITLE
Cannot "Install" DotFiles

### ISSUE THREAD

**Issue by tayron1** [Axarva/dotfiles-2.0#154]
**Error**
`ln: failed to create symbolic link '/usr/lib/libasan.so.6': File exists`

**System Information** 
```tayron@tayron-ms7758

OS: Garuda Linux
Host: MS-7758 1.0
Kernel: 5.18.9-zen1-1-zen
Uptime: 12 mins
Packages: 1434 (pacman)
Shell: bash
DE: Plasma 5.25.2
WM: KWin
 WM Theme: Sweet-Dark
 Terminal: konsole
 CPU: Intel i7-3770K (8) @ 3.9GHz
    GPU: Intel IvyBridge GT2 [HD Graphics 4000]
         GPU: NVIDIA GeForce GTX 770
          Memory: 3.36GiB / 15.53GiB
```

**Comment by Axarva** [comment]
Delete line 86 (the line says: sudo ln -s /usr/lib/libasan.so.8 /usr/lib/libasan.so.6 # Hack to make tint2 work for now.) in the install-on-arch.sh file, then run it. That should solve it.

**Comment by tayron1** [comment]
thank you. trying the install rn without the line

**Comment by tayron1** [comment]
Now it gives me
```[Aur:2]  picom-jonaburg-git-0.1-5  rofi-greenclip-4.2-2

:: (0/2) Downloaded PKGBUILD: picom-jonaburg-git
:: (0/2) Downloaded PKGBUILD: rofi-greenclip
-> error fetching picom-jonaburg-git: fatal: could not create work tree dir 'picom-jonaburg-git': Permission denied
context: exit status 128

error fetching rofi-greenclip: fatal: could not create work tree dir 'rofi-greenclip': Permission denied
context: exit status 128

```

**Comment by tayron1** [comment]
trying with Pacu rn. Maybe that helps

**Comment by tayron1** [comment]
![image](https://user-images.githubusercontent.com/50525948/178102624-34628c06-cd9c-4dc8-a57c-83372e6304c0.png)
What does `PLEASE MAKE .xinitrc TO LAUNCH` mean?
I'm completely new lol

**Comment by tayron1** [comment]
hm ok only Conky Launched

**Comment by Axarva** [comment]
Looking at your last screenshot, I believe installation was successful. I’m not sure about conky since the configs don’t use conky at all.

**Comment by zabapuen** [comment]
Hello, I've been using your scripts for a while and made some changes regarding the this issue:

`if ! [ -f /usr/lib/libasan.so.6 ]; then
    sudo ln -s /usr/lib/libasan.so.8 /usr/lib/libasan.so.6 # Hack to make tint2 work for now.
fi`

**Comment by Axarva** [comment]
Thank you! I didn't have the if statement, which probably broke the install script for a few people. I'll put that in immediately.
