### ISSUE TITLE
Can't to remove bar which is in the bottop side of screen

### ISSUE THREAD

**Issue by sevbo2003** [Axarva/dotfiles-2.0#156]
Can anyone help I can't remove bar which is in the bottop of screen

**Comment by Axarva** [comment]
Use “super+b” to close all bars. If you just don’t want the bottom bar at all, edit “~/bin/bartoggle” and remove the line containing the word “panellauncher”.

Hope this helps.

**Comment by sevbo2003** [comment]
Ok Next problem. How can I change text messages like Goodbye Axarva

**Comment by Axarva** [comment]
That is set in ~/.config/rofi . I can’t remember which file exactly so try opening a text editor amd searching for the word “Axarva” and replace it with anything you want.

**Comment by Axarva** [comment]
Assuming this has been solved. Closing this for now.
