### ISSUE TITLE
Quotes on centerlauncher.

### ISSUE THREAD

**Issue by cafunedoces** [Axarva/dotfiles-2.0#16]
Good afternoon Sir,
I changed the **quotes.json** text inside the **~/.config/eww/script/quotes.json**, but most of the times it doesn't work, like this 
![2021-02-16_14-49_1](https://user-images.githubusercontent.com/79163185/108102180-f982b500-7066-11eb-9e03-d2c8eaee2244.png)

this is a example of my change:
{
    "text": "I have a dream...",
    "author": "Martin Luther King"
  }

I beggined the file with **[** in the first line, and finished with **]** in the last file line.
I just used about one hundred quotes, changing each one.
I already checked if I made a mistake in the file, but is just like your, just the text and author changed.
Sometimes shows me up my quotes, most time don't.

And how can I prevent my monitor to get in to black screen mode? I made a /etc/X11/xorg.conf.d/10-monitor.conf** with this line:

Section "Monitor"
    Identifier	"eDP-1"
    Option      "DPMS" "false"
EndSection

Section "ServerLayout"
	Identifier "ServerLayout0"
	Option	"StandbyTime"	"0"
	Option	"SuspendTime"	"0"
	Option	"OffTime"	"0"
	Option	"BlankTime"	"0"
EndSection

Didn't work. Also used **xset s off**. Still blacking after some time.
I tried dconf to change too.
Thanks for your time.

**Comment by Axarva** [comment]
Does the blacking happen when you’re using the inhibitor? Or does it happen without it?

Could you tell me if you can parse the new quotes.json file using jq?

**Comment by morenoled** [comment]
even with the **inihibitor** on.

yes, I can parse it. Take a look.
![quotes](https://user-images.githubusercontent.com/78452560/108189799-ea941500-70ef-11eb-9e3a-7a4f5d90ee4c.png)

**Comment by Axarva** [comment]
How about the command `xset -dpms`? Does this prevent screen blanking?
As for the json, if it can be parsed by `jq`, then replacing the `~/.config/eww/scripts/quotes.json` file with the new file and then copying it over to `/tmp/xmonad/quotes/quotes.json` should load up the new quotes.

**Comment by morenoled** [comment]
Like I sad, I edited your `quotes.json` file and kept the same parameters. As I told you, sometimes shows me my quotes, most time don't. Even when I copy to `/tmp/xmonad/quotes/quotes.json`.



when I launch `xset -dpms` still blanking.
when I run `xset q`, this happens:
![a](https://user-images.githubusercontent.com/78452560/108198905-fcc78080-70fa-11eb-82d1-c672ad699963.png)

So, I did `exec xset s 0 0 dpms 0 0 0` and stop blanking, and `xset q` shows me this

![2021-02-17_10-00](https://user-images.githubusercontent.com/78452560/108207864-0fe04d80-7107-11eb-9db1-5ca51d2ffa94.png)


Then, I puted on` xmonad.hs` this `  spawnOnce "exec /usr/bin/xset s 0 0 dpms 0 0 0"`, rebooted and this happens:

![b](https://user-images.githubusercontent.com/78452560/108206806-ae6baf00-7105-11eb-92d8-87e6b1c0663b.png)

So, the `dpms 0 0 0` works, but the `xset 0 0` don't. but when I run it manually it works fine.

**Comment by morenoled** [comment]
So the real problem is, disable screen saver automatically. I made it on dconf, but nothing change.
![2021-02-17_10-43](https://user-images.githubusercontent.com/78452560/108212774-0954d480-710d-11eb-8b82-c09c733bcf98.png)

**Comment by morenoled** [comment]
I FOUND IT!!!!!!
Its the `~/bin/lock.sh`.
I just change de value from 500 to 0 and _voilà_.
Thanks again my friend, have a nice day.

**Comment by Axarva** [comment]
> I FOUND IT!!!!!!
> Its the `~/bin/lock.sh`.
> I just change de value from 500 to 0 and _voilà_.
> Thanks again my friend, have a nice day.

That is weird, I'll try integrating this part into the inhibitor module soon. Are you sure that just running the command `xset s 0` later through your shell doesn't stop this?

**Comment by Axarva** [comment]
I just found out it *does* stop it, and I added it to the inhibitor module. Please `git pull` the repo and then copy over the `bin/inhibit_active` script to your `~/bin`. That should fix the screen blanking.

**Comment by Axarva** [comment]
As for the quotes.json issue, I think I have figured what the bug is.
If you look into the `~/.config/eww/scripts/quotes` script, you see that I generate a random number between 1 to 500 at line 2 of the script.
![image](https://user-images.githubusercontent.com/66304313/108234593-0db0da00-716d-11eb-8d63-0c27c103bc56.png)

This is what gets passed to `jq` as the index of the json array. That means any array that you put into the quotes file must have an index of at least 500 to work correctly each time. You'll have to edit the number to match the number of items in your json file. I believe that'll solve it.

**Comment by Axarva** [comment]
Closing because I believe everything is figured out now :smile:
