### ISSUE TITLE
Nothing changed

### ISSUE THREAD

**Issue by Soommeeoonnee** [Axarva/dotfiles-2.0#161]
**Describe the bug**
so i did pretty much everything but nothing has changed

**Desktop (please complete the following information):**
 - OS: Linux mint
 
![path](https://user-images.githubusercontent.com/110643000/182977282-089e503e-c63f-4f7d-8869-6296d6544094.jpg)
the .config file
![config](https://user-images.githubusercontent.com/110643000/182977361-49713c03-b26a-43ab-8646-737a4dc30336.jpg)

**Comment by zabapuen** [comment]
Try selecting Xmonad in the login manager! Instead of cinnamon or whatever you're using...

**Comment by Axarva** [comment]
> Try selecting Xmonad in the login manager! Instead of cinnamon or whatever you're using...

Exactly. Will close this.
