### ISSUE TITLE
Rounded corners. 

### ISSUE THREAD

**Issue by agonzal** [Axarva/dotfiles-2.0#17]
How did you get your corners to be rounded? In my setup they are straight corners and would love to have them rounded like in your screenshots. please advise thanks!

**Comment by morenoled** [comment]
your `picom` effects are working fine? like transparency and shadowing? If not, try to change the `spawnOnce "picom ?"` in **xmonad.hs** (in my case, line 331), to `spawnOnce "picom -f"`.
Then, run `xmonad --recompile` and reboot.
This is how I made it happen.

**Comment by morenoled** [comment]
By the way, I'm using **jonaburg-picom-git**.

**Comment by Axarva** [comment]
It's exactly as @morenoled described, although I don't see where the line `spawnOncwe "picom ?"` occurs in the file. And yes, the specific fork of picom, (`picom-jonaburg-git` on the AUR) is needed for the transitions. A link to the picom fork repository is [here](https://github.com/jonaburg/picom).

**Comment by morenoled** [comment]
sorry, it because I don't remember the rest of the script. The **?** means, "Whatever is there", =].
I forgot to specify that =/.

**Comment by agonzal** [comment]
I have literally been running Xmonad for 2 days now. My spawnOnce line already had `picom -f` and I went ahead and compiled jonaburg-picom from source and installed that on my system (as well as removed the existing rpm providing picom). One thing I did notice was the fact that the corresponding picom.conf was in ~/.config/picom.conf and not ~/.config/picom/ so I have made that change, but I still do not see any transparency or shadows or round corners. 


![image](https://user-images.githubusercontent.com/8383391/108609892-f862c800-7385-11eb-9253-0e92a6b0d723.png)


I am running v8 of picom from that repo you directed me too. 

here is the corresponding section you brought up from my xmonad.hs 


myStartupHook = do
  spawnOnce "exec ~/bin/bartoggle"
  spawnOnce "exec ~/bin/eww daemon"
  spawn "xsetroot -cursor_name left_ptr"
  spawn "exec ~/bin/lock.sh"
  spawnOnce "feh --bg-scale ~/Pictures/wallpapers/lovelace.png"
  spawnOnce "/usr/local/bin/picom -f"
  spawnOnce "greenclip daemon"
  spawnOnce "dunst" 


The install also came with a picom-trans but that seems to be a shell script, and I don't know what to really do it with it.

**Comment by agonzal** [comment]
I guess I can run picom-trans and it does indeed make a window that I click on transparent. So apparently that is working.

**Comment by Axarva** [comment]
Did you issue `xmonad - -recompile` after making changes to your config file? Did you then log out of xmonad and then log in? And what happens when you issue `picom -f` directly in your terminal?

**Comment by agonzal** [comment]
I did recompile after saving the changes to xmonad.hs and took things a step further and rebooted the system. There appears to be an error (level WARN)  in the config file Unfortunately the error message does not give me further input beyond the following: 

[ 02/20/2021 21:14:38.760 parse_config_libconfig WARN ] Invalid blur method dual_kawase, ignoring.

That message followed by "FATAL_ERROR another compositor manager is already running. 

> picom -f 

[ 02/20/2021 21:14:38.760 parse_config_libconfig WARN ] Invalid blur method dual_kawase, ignoring.
[ 02/20/2021 21:14:38.764 session_init FATAL ERROR ] Another composite manager is already running

This is what I get when running picom with the f switch from the terminal. I can attach the config I am using but I did not make any modifications to the one you provided. it currently resides at ~/.config/picom/picom.conf

**Comment by agonzal** [comment]
Based on https://github.com/yshui/picom/pull/361 dual_kawase blur is exactly what I need to get the rounded corners, and for some reason it says it is not an accepted blur. I compiled that repo from source, but maybe I did something wrong? Will try again shortly.

**Comment by Axarva** [comment]
That pull request is still not merged completely, so it seems that it won’t work. The fork that the current config file in this repository is tried and tested on, is [**picom-jonaburg-git**](https://github.com/jonaburg/picom). Please try the binary from that specific fork and compare results.

**Comment by agonzal** [comment]
That is what I am running. It was mentioned yesterday so I went and compiled it following the instructions. It installed a binary to /usr/local/bin/picom and a shell script to /usr/bin/picom. I can use the picom-trans script to make windows transparent. On another note, I just ran into the workspaces.tint2rc losing color, the fix you mention worked once, but upon reboot, the issue came back even though your fix is still present.

Is it against the release v8 or a clone of the current repo state? That could be where I messed up as I downloaded v8 release. let me clone the repo and build again.

**Comment by agonzal** [comment]
That was the issue. I built the v8 release instead of cloning the repo and building the branch next. Rounded corners have been enabled. My bad. Now to fix this damn workspaces.tint2rc losing colors, lol. Thanks for being  patient with me, much appreciated.

**Comment by agonzal** [comment]
cloning the repo, and building the code in the 'next' branch worked. Rounded corners have been achieved. Thank you for your assistance and patience. I should have noticed that you put -git in your version! I have made quite a few customizations to the layout, but overall you provided the foundation, thanks!

**Comment by Axarva** [comment]
Ah, glad you got everything fixed! About the workspace panel... could you perhaps show me where exactly did you add the line?

**Comment by Axarva** [comment]
444bd53 has solved the bar issues. Just updated my tint2 fork to fix the bug. It should be fine now.
