### ISSUE TITLE
Shutdown not working on 1366x768 screen 

### ISSUE THREAD

**Issue by B0TRICK** [Axarva/dotfiles-2.0#171]
Screenshot
![IMG_20221125_090703](https://user-images.githubusercontent.com/113281799/203896917-5d44c8bd-b658-42bb-aed1-052e4936b067.jpg)
Please do something :(

**Comment by FlyingWolf11** [comment]
@B0TRICK 
Edit your ~/.config/rofi/black_powermenu.rasi and add the line:
`border: FFFFFF;`

**Comment by B0TRICK** [comment]
not working

**Comment by FlyingWolf11** [comment]
@B0TRICK 
Is still the same message appearing or is the shutdown after the message not working?

**Comment by B0TRICK** [comment]
Thanks now it's working:)
