### ISSUE TITLE
What is the purpose of the icon with the eye?

### ISSUE THREAD

**Issue by pat3plol** [Axarva/dotfiles-2.0#172]
I found that the icon with the eye is the result of the inhibitor.sh script. From what I can see, this script displays an icon with a crossed out eye when xautolock is working and an icon with a regular eye when xautolock is not working.

Xautolock is started automatically when the system boots, so the icon will always be the same.

So what is its use?

**Comment by l6174** [comment]
It is used to keep the display from turning on when you are watching a video or reading something. You can toggle it on or off by pressing meta + z and meta + shift + z. That eye icon is just an indicator of whether the inhibitor is on or off nothing happens when you click it.
