### ISSUE TITLE
Notebook lid.

### ISSUE THREAD

**Issue by morenoled** [Axarva/dotfiles-2.0#18]
something is happening when I close my notebook lid.
my SSH connection goes down, together with my no-ip service in systemctl.
When I open it, I recover my connection.
How can I fix that? Because my session isn't suspended. 
thanks again.

**Comment by Axarva** [comment]
I have no clue, to be honest. That specific issue seems to be more related to your init system rather than the window manager. I suggest you try looking in forums for this answer. If in any case, this happens to be the issue of the window manager, I'll gladly look into it. Good luck!

**Comment by morenoled** [comment]
Thanks for the guidance ... I will check that.
If I find the solution I will post here.
Be safe.

**Comment by morenoled** [comment]
Fixed!
Edit this.
`user$ sudo vim /etc/systemd/logind.conf`
Just uncomment those lines.

```
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
```
And then, run
`user$ sudo systemctl restart systemd-logind`

Or just restart.

Thanks for your guidance, it was really on my init system.
