### ISSUE TITLE
picom git error

### ISSUE THREAD

**Issue by Tetroner9** [Axarva/dotfiles-2.0#196]
When running the script you will get following error 
Repository AUR:
    1) betterlockscreen  2) betterlockscreen-git  
Enter a number (default=1): 
error: could not find all required packages:
    picom-jonaburg-git (target)

**To Reproduce**
1. Run script normally until better lockscreen step

**Expected behavior**
Proceed with normal installation

**Desktop:**
 - Arch Linux
 
**Fix**
Change line 71 (for arch install script) to $HELPER -S picom-git\
and when running just select defaults

**Comment by jzitnik-dev** [comment]
Yeah, for some reason jonaburg's fork of picom is not in the aur anymore.
It is fixed now.
Also if you just install picom-git, you will not have window animations that are in jonaburg's fork of picom.

If you have already installed it and you want animations you can uninstall the current picom using `yay -R picom-git` and install jonaburg's fork like this:
```bash
git clone https://github.com/jonaburg/picom
cd picom
makepkg -si
```
**Make sure to not run it as root**
