### ISSUE TITLE
Rofi/Clipboardy error

### ISSUE THREAD

**Issue by morenoled** [Axarva/dotfiles-2.0#21]
In the `~/bin/clipboardy` I had to change the file.
```
#!/bin/bash
rofi -modi " :greenclip print" -show " " -run-command '{cmd}' -theme ~/.config/rofi/launchers/text/style_2.rasi
```
This was showing me a error, because **~/.config/rofi/launchers/text/style_2.rasi** doesn't exist and **greenclip** was not installed. So I installed the **grenclip** and edited to `... ~/.config/rofi/launcher/black_launcher.rasi`, or .`... ~/.config/rofi/launcher/style.rasi`to make it run, and restarted the pc.
Now it's ok. 
I think you should check your repository file.
Have I nice weekend, see ya.

**Comment by Axarva** [comment]
Thank you so much! Addressed in commit 844c770
