### ISSUE TITLE
Centerlaunch and Sidebarlaunch issues

### ISSUE THREAD

**Issue by morenoled** [Axarva/dotfiles-2.0#23]
Here I'm again =]
So, my problem is:
I had to reinstall my system. Everything is looking great, as usual, but when I try to shutdown or reboot using the icons on centerlaunch or sidebarlaunch, nothing happens.
when I use mod+shift+q, everything works fine. I can use the icons to do this.
I have oh-my-zsh, as usual.
By the way. When I run `systemctl logout`, nothing happens too. I'm using `killall -u username`. I think this is not the best way to logout, but I'm using it.
And yes, I had change all the `doas` to `systemctl`.
I'm running Arch, with Xorg. No gdm, no Gnome. I'm starting xmonad from terminal this time.
Thanks again my friend.

**Comment by Axarva** [comment]
Could you please check the scripts in `~/.config/eww/scripts` that are related to the issue? You could find clues to solving this there.

**Comment by GideonWolfe** [comment]
Hello, I have kind of an unrelated question about your `eww` setup, which I've taken inspiration from. How do you go about "toggling" a `eww` window?

I want to be able to click on my `polybar` to toggle my `eww` sidebar, but how can I programatically determine whether to run `eww open` or `eww close`?

**Comment by morenoled** [comment]
sorry for take too long to answer...
I had a lot of things to do this month. New job, moving the office to another place, etc.
Let's go.
I make those changes in `~/.config/eww/scripts` soon I had installed everything, replacing `doas` to `systemctl`.
![2021-04-03_16-49](https://user-images.githubusercontent.com/78452560/113493441-b618c480-94b5-11eb-8b0c-54994b42242b.png)
By the way, the logout command isn't working. I'm using `killall -u moreno` to exit session. I think there is another way to do this, more "elegant" way.

**Comment by katzeyurei** [comment]
> sorry for take too long to answer...
> I had a lot of things to do this month. New job, moving the office to another place, etc.
> Let's go.
> I make those changes in `~/.config/eww/scripts` soon I had installed everything, replacing `doas` to `systemctl`.
> ![2021-04-03_16-49](https://user-images.githubusercontent.com/78452560/113493441-b618c480-94b5-11eb-8b0c-54994b42242b.png)
> By the way, the logout command isn't working. I'm using `killall -u moreno` to exit session. I think there is another way to do this, more "elegant" way.

I have a kinda similiar issue, I cant shutdown, reboot, suspend, logout, from the sidebarlaunch, after the y/n confirmation nothing happens, I thought it was the scripts, but when I manually run those scripts in the eww config dir, they're working properly. So idk where's the problem

**Comment by Axarva** [comment]
Are you sure about the scripts working when you manually execute them? That seems weird....
Please provide further information.

Could you go through the script again and make sure all of it is fine? Or perhaps copy and paste the current state of the script on your machine here?

**Comment by katzeyurei** [comment]
here is my eww folder [https://drive.google.com/drive/folders/1AzL0N0ZtA4u0UCz29yXNpiPU78hczHXQ?usp=sharing](url)
I tried to change the sidebar button, so when I click on the power button, it will spawn the powermenu.sh, but yeah it doesnt work as well it spawn the menu but when I click on one of the buttons, they didn't work, and then I made a shortcut to open the powermenu.sh script using my dwm config and it works perfectly, so I think it's the eww

**Comment by Axarva** [comment]
I'm sorry for being a bit late, wifi is hard to manage to get in the place I am at :)

That is really weird, did you use the eww binary provided in this repository or compiled it yourself?

**Comment by katzeyurei** [comment]
> I'm sorry for being a bit late, wifi is hard to get in the place I am at :)
> 
> That is really weird, did you use the eww binary provided in this repository or compiled it yourself?

I use the provided one, well I think it's ok, I already made a keybind shortcut in my wm ocnfig to spawn the powermenu without using eww and yeah Its perfect

**Comment by morenoled** [comment]
> Are you sure about the scripts working when you manually execute them? That seems weird....
> Please provide further information.
> 
> Could you go through the script again and make sure all of it is fine? Or perhaps copy and paste the current state of the script on your machine here?

When I run `killall xmonad`, the terminal reply to me there is no process located.
I still have to use `killall -u moreno`

**Comment by Axarva** [comment]
Could you try using `loginctl terminate-session $(loginctl session-status | head -n 1 | awk '{print $1}')`?

**Comment by Axarva** [comment]
I'll close this for now. Please comment again and I'll reopen.

**Comment by redgloboli** [comment]
Hi,

i have exactly the same issue, logout.sh called directly works as expected, if i use the logout button in eww it doesn't work, it asks Are You Sure? and no matter what i enter it does nothing, not even the message with the options pops up if i enter "maybe" or something else.

It works in my zsh shell by calling it directly.

Same goes for reboot/suspend script.

I'm launching xmonad with sddm if this does matter.

For the issue: killall xmonad - no process located, the solution is to use killall xmonad-x86_64-linux on my archlinux system.
