### ISSUE TITLE
Some problem with widgets and cpu usage(tint2)

### ISSUE THREAD

**Issue by Muhammad-Mirab** [Axarva/dotfiles-2.0#24]
Hi, first of all thank you for this awesome theme :)

System Information:
    - OS: Arch 2021

I have some problems with the widgets:
![Screenshot from 2021-03-20 01-03-36](https://user-images.githubusercontent.com/56149328/111844911-2271c080-8919-11eb-87e9-1680ef4377a4.png)
It's in a bad shape and It's full screen...
And also in the sidebar, the audio controller isn't working:
![image](https://user-images.githubusercontent.com/56149328/111845169-93b17380-8919-11eb-8d86-657a13a530e0.png)

There is another problem with tint2 which leads up to high CPU usage but when I use the "CTRL + B" shortcut which disables  launcher and clock etc. the tint2 will disappear from htop log... and it was mentioned in another issue, but I thought it's worth mentioning...
![image](https://user-images.githubusercontent.com/56149328/111845744-b8f2b180-891a-11eb-942a-b23500f63cd6.png)

Thanks :)

**Comment by Axarva** [comment]
I'm sorry for being late to reply. I see issues with rendering of widgets. Did you use the same picom fork and the picom.conf as listed in the README? 

As for the bar, I have no clue. Could you try locally compiling [my fork of tint2](https://github.com/Axarva/tint2-1) and see the results with that binary?

**Comment by Muhammad-Mirab** [comment]
Don't be sorry :)
I'll do these as soon as possible, and I will post the result here, thank you!

**Comment by DominikVisca** [comment]
The black background of the launcher overlay seems originated in the missing "eww blur_full" command. I also tried compiling the eww from source.

**Comment by Axarva** [comment]
Hello there again, I believe @DominikVisca 's solution might be helpful, as well as checking what fork of the picom compositor you are using. `picom-jonaburg-git` is the one that supports this config properly. Also do check your `~/.config/picom.conf` file.

The bar issue has quite recently been resolved in #20 thanks to @greenbourne277 

Hope this might be of help.

**Comment by morenoled** [comment]
I had to comment the `~/.config/tint2/icons.tint2rc` to fix the high CPU usage.

**Comment by Axarva** [comment]
This is now completely fixed. Please `git pull` this repository, then issue
`cp ./bin/tint2 ~/bin/tint2`
`cp ./bin/bartoggle ~/bin`

Refresh the bars with `Mod + B`. This issue should now be gone with no tweaking to the configs. Cheers to @DominikVisca without whom this issue couldn't have been solved.
