### ISSUE TITLE
No blur in dashboard

### ISSUE THREAD

**Issue by dark-dryu** [Axarva/dotfiles-2.0#25]
When I open the dashboard, the background is a solid color. I was expecting it to display my background blurred.
By reading the config/eww files I do not understand how it works. Do I have to create a blurred image of my background  and insert it in the `<window>` or `<def>` object named "blur_full"?

**Comment by Axarva** [comment]
No. Did you use the `picom.conf` file provided in the repository? That file tells your compositor to blur the `blur_full` window.
Also, please use the picom-jonaburg fork of picom for best results. Good luck?

**Comment by dark-dryu** [comment]
No, that was the thing, thank you! I can confirm that normal picom does not work properly and the picom-jonaburg fork is needed.
