### ISSUE TITLE
Issue with interface not refreshing

### ISSUE THREAD

**Issue by nephomancer** [Axarva/dotfiles-2.0#26]
Hey @Axarva,

Just installed XMONAD using @savvynik's video on Arch Linux, completely fresh installation on VirtualBox on Windows10. I also installed NVIDIA drivers and selected "3" to skip when offered intel/amd drivers.

My issue is when using the Super+Shift+Enter it loads the terminal, but will not refresh my screen so I cannot check what I have typed, unless I press Super+Shift+Enter again to load a second terminal it will show what I had typed in the first terminal.

This happens with all visual elements, was just giving terminal as an example.

![Testing](https://imgur.com/PZGDivo.gif)

Did I miss something?

List of my installed packages: https://ghostbin.co/paste/8aup

**Comment by Axarva** [comment]
@SavvyNik himself reported that this setup doesn't work as expected on a virtual machine at all. I'd say it's quite a feat that you have got it to work to this extent on a vm. I do not know what makes this setup so virtual machine-unfriendly, and I don't know what's causing this interface issue.

All I can suggest is:

1. Make sure all the vm drivers and kernel modules are properly installed.
2. Recompile xmonad with `xmonad --recompile` after the first step.
3. Reboot the vm to see if these steps are of any help.

**Comment by nephomancer** [comment]
Thanks for the advice, VM drivers and kernal modules were up to date, just did the following steps:

1. locate xmonad.hs (locate didn't work, installed sudo pacman -S mlocate, then did an updatedb)
2. found file in /home/username/dotfiles-2.0/xmonad/xmonad.hs
3. went to that dir, ran sudo xmonad --recompile (error, can't find file in /root/.xmonad/xmonad.hs)
4. ran cp xmonad.h /root/.xmonad/
5. ran cd /root/.xmonad
6. xmonad --recompile (successful)
7. logged in with user
8. ugly errors (can't find .xmonad/build, .hs has been changed, error loading shared libraries (libHSxmonad-contrib), xinit connection to X server lost)
9. lost hope

I did not realise @SavvyNik reported about that with VMs haha! I generally try to not give up, but I'm going to run a new fresh VM and try again a bit slower incase I did miss anything, if that fails I'll try it on a dedicated machine rather than a VM.

**Comment by Axarva** [comment]
XMonad is supposed to be recompiled with your user’s privileges alone. Never use root privileges to do so. The file should be located in /home/$USER/.xmonad/, not anywhere near the root user’s directory. I hope you have better luck this time!

**Comment by Axarva** [comment]
Removed the help wanted label as help was wanted only for virtual machine friendliness. An issue has been opened just for that purpose, so keeping the label here as well wasn't necessary.

**Comment by Axarva** [comment]
Mm, I’ll be closing these for the meantime since @Kellegram ’s solution with picom configs seems to be working for everyone.
