### ISSUE TITLE
VirtualMachine Friendliness

### ISSUE THREAD

**Issue by Axarva** [Axarva/dotfiles-2.0#27]
**Describe the bug**
The configuration does not seem to work at all in a vm environment.

**To Reproduce**
Install the configs on a linux virtual machine.

**Expected behavior**
The configuration to work properly.

**Screenshots**
None.

**Desktop:**
 - OS: Any [Bug confirmed for ArchLinux, suspected on other distributions]

**Additional context**
None.

**Comment by NikolaTesla13** [comment]
I installed this on an Arch vm but everything is very laggy, I can't even type. I'm using vmware. My virtual machine specs are 4 cores with 16gb of ram.

**Comment by Axarva** [comment]
I wish I could fiddle around with virtualmachines currently, but other personal issues demand my attention at the moment. If anyone could look into this for now, it'd be of great help.

**Comment by bhugoo** [comment]
I also having troubles using a vm. Same situation as @NikolaTesla13, I can open the terminal (takes about forever though) but can't type anything. How can I navigate around and edit files when it logs in directly when I enter username and password?

**Comment by iSparsh** [comment]
can you try pressing ctrl + alt + f4? it opens a tty screen. Maybe fiddle around from there?

**Comment by bhugoo** [comment]
Yea it does, I gotta log in again though and it just opens the desktop again, this time totally empty. However I guess this is me being new to linux and not anything related to this project.

**Comment by iSparsh** [comment]
its gonna be a little difficult, but try if you can open your .xinitrc file. if you can just paste the contents over on pastebin and comment again here..
General points:-
remove these lines from `.xinitrc` if they exist
```
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
```

if you don't you may wanna check your xsession or xprofile files.

**Comment by Axarva** [comment]
If you're using `startx`, could you also make sure that the only contents in your `~/.xinitrc` is `/usr/bin/xmonad` ?

**Comment by Kellegram** [comment]
I have some theories, will investigate a few things first tho before making any claims, will be back on that.

**Comment by Kellegram** [comment]
How it runs on my machine with those settings (I have a shitty motherboard that breaks 64 bit VMs, yours might run better!):
https://streamable.com/efexay

**Comment by Kellegram** [comment]
The main thing here is the "glx" backed. This is what causes the freeze. Other stuff is just helping with performance.

**Comment by Nikhil-John** [comment]
@Axarva I have the same problem. After asking for the paru installation where I give yes, it shows failed at build(), aborting and then stops completely. I'm running Arch on Virtual Box.
Is this a problem with Virtual Box?
Will appreciate any fixes..
Thanks

**Comment by Kellegram** [comment]
> @Axarva I have the same problem. After asking for the paru installation where I give yes, it shows failed at build(), aborting and then stops completely. I'm running Arch on Virtual Box.
> Is this a problem with Virtual Box?
> Will appreciate any fixes..
> Thanks

Are you able to show more of the error? This is too vague. I installed this setup on VirtualBox multiple times and it doesn't fail to build, however in general VirtualBox is garbage, especially the 3D Acceleration is non-existent so expect picom to cause lags, you need to use the picom.conf in VM folder that I made for it to be in any way usable.

**Comment by Nikhil-John** [comment]
@Kellegram  Hi, I'm attaching a video of my installation attempt.

PS: I had installed the NVIDIA tools required as per SavvyNik's video on YoutTube and hence I skipped the video drivers part during the installation.

Thanks


https://user-images.githubusercontent.com/64088567/120098715-20b44c80-c155-11eb-8b2d-013c9deb581a.mp4

**Comment by Kellegram** [comment]
@Nikhil-John Please install base-devel via pacman then try again.

**Comment by Kellegram** [comment]
This is an error that can apparently be fixed by running `rustup install stable` then `rustup default stable` but I don't get why you would see this error, I never needed to install `rustup` in the first place.

**Comment by Nikhil-John** [comment]
@Kellegram Definitely will try that again. Just to know... if I do `rustup install stable` and `rustup default stable` then should I type "no" where it asks to if I need to install Paru? Also before I do the above two commands do I have to install `rustup`?

P.S: Sorry, I'm new to Arch and has only been a few days...😅

**Comment by Axarva** [comment]
Hmm, getting the base-devel package should have fixed this. This is getting weird. First it was rofi-git, now paru...

**Comment by Nikhil-John** [comment]
> This is an error that can apparently be fixed by running `rustup install stable` then `rustup default stable` but I don't get why you would see this error, I never needed to install `rustup` in the first place.
> 
> (Well, I guess I did, but something I install in base arch OR in this asks me to get this).

Well this worked actually.. Thing is, I hadn't installed zsh on my system.. So it showed the following and quit out...
May I know what I must do next?
I did install zsh by doing `sudo pacman -S zsh`. How do I continue with the installation?
![Arch Linux XMonad VM](https://user-images.githubusercontent.com/64088567/120152669-629fca00-c20b-11eb-8096-e04a2fe90c59.png)

**Comment by Nikhil-John** [comment]
> Hmm, getting the base-devel package should have fixed this. This is getting weird. First it was rofi-git, now paru...

I had base-devel installed when I installed Arch on my VM... So that shouldn't have been a problem... Then again just to be sure I did a reinstall of it and yet the probelm persisted... It did work upto the point where it asked me to install zsh after doing `rustup install stable` and `rustup default stable` as suggested by @Kellegram

**Comment by Kellegram** [comment]
@Nikhil-John I think I see what's going on. You are using the modified branch aren't you? My pull requests to fix things were only to main branch, my guess is @Axarva did not mirror some changes to the installer to modified branch, hence the issue. Using the installer from main branch is a better idea, although also keep in mind that regardless of which one you choose, unless you can get 3D acceleration to work in virtual box, picom, the compositor, will run quite poorly.

**Comment by Nikhil-John** [comment]
> @Nikhil-John I think I see what's going on. You are using the modified branch aren't you? My pull requests to fix things were only to main branch, my guess is @Axarva did not mirror some changes to the installer to modified branch, hence the issue. Using the installer from main branch is a better idea, although also keep in mind that regardless of which one you choose, unless you can get 3D acceleration to work in virtual box, picom, the compositor, will run quite poorly.
Yea I tried with the modified branch... will try with the main branch next. Will check and report the status.
Thanks 🤗

**Comment by Axarva** [comment]
@Nikhil-John Sorry for the inconvenience. The modified branch should function just fine now. Please do give it a retry if you feel like it, after all, it is just one `git pull` away.

**Comment by Axarva** [comment]
Well, since I haven’t heard of any more issues with virtualmachines after @Kellegram had a look into it, I will assume this long-standing bug has been fixed. I’ll be closing this, but it will remain a pinned issue on the repo. Thank you everyone who gave a look into this, and specially @Kellegram !
