### ISSUE TITLE
error making: rofi-git

### ISSUE THREAD

**Issue by s-thomas99** [Axarva/dotfiles-2.0#28]
I can't install it. 
I get this as a summary of failures:

  3/17 rofi / helper_pidfile test                              FAIL           0.01s     exit status 1
11/17 rofi / helper test                                          FAIL           0.03s     exit status 1
12/17 rofi / helper_expand test                             FAIL           0.04s     exit status 1
13/17 rofi / helper_config_cmdline_parser test     FAIL           0.04s     exit status 1
15/17 rofi / helper_tokenize test                           FAIL           0.05s     exit status 1

Can anyone help me, i don't know what to do to fix this issue.

**Comment by Axarva** [comment]
Shouldn't this go into the issues section of [rofi](https://github.com/davatorium/rofi)?

I'd say please check that all the required dependencies are present and try rebuilding.

**Comment by johnbarney** [comment]
Those are all locale tests. Ensure you've selected the correct locate in /etc/locale.gen then run locale-gen.

**Comment by s-thomas99** [comment]
Thanks! I got it working.
