### ISSUE TITLE
Blur window fails to blur

### ISSUE THREAD

**Issue by GideonWolfe** [Axarva/dotfiles-2.0#29]
**Describe the bug**
The blur window should hide the window contents

**To Reproduce**
1. Add definition for `blur_full` in `eww.xml`
2. Add opacity rule for `eww-blur_full` in picom.conf
3. `eww open blur_full`

**Expected behavior**
The contents of the window are blurred

**Screenshots**

When `picom` is not running, `eww open blur_full` shows a black screen, as expected.

Here's what my desktop looks like normally with `picom` running

![image](https://user-images.githubusercontent.com/32942052/113245050-07814380-926b-11eb-860c-f6cf103ac532.png)

And here is what it looks like when I open `blur_full`

![image](https://user-images.githubusercontent.com/32942052/113245120-254ea880-926b-11eb-9852-9b30d0b1e237.png)

There is basically no change, although the window is still there overlaying my windows. Running `xprop` and clicking the screen shows `eww-blur_full` is there.

I would like it to hide other windows in the background and simply blur the wallpaper, much like the behavior when a program is fullscreened, like so

![image](https://user-images.githubusercontent.com/32942052/113245339-9d1cd300-926b-11eb-9bee-d2c6a9be80e7.png)

Even though there are other windows on the screen, they are hidden. I think this is the behavior you have? 

**Desktop (please complete the following information):**
 - OS: Arch Linux + i3

**Comment by Axarva** [comment]
Hmm, I'd say fiddling around with your compositor's settings should be of help. Are you using picom-jonaburg-git? I've had best results with that fork.

**Comment by GideonWolfe** [comment]
Ah, it seems to be due to the following section in my `picom.conf`.

```
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];
```
