### ISSUE TITLE
Add an option to download with paru in arch linux install script

### ISSUE THREAD

**Issue by ashishbinu** [Axarva/dotfiles-2.0#30]
I was installing it with arch linux script and it asks to install `yay` for downloading from `aur` but I use `paru`. Can you guys add an option to install those needed packages from aur using `paru`.

Below was the message which came in terminal.
```
Would you like to install yay? Say no if you already have it (step necessary because well, we need some stuff) [yes/no]: yes
```

**Comment by Axarva** [comment]
Hm, I would like to do so, since I hear yay is no longer maintained. I have no experience whatsoever with paru, so this might take some time.

**Comment by ashishbinu** [comment]
There are not much difference in paru and yay in terms of command used. There might be slight difference.

**Comment by Axarva** [comment]
The repository has now transitioned from yay to paru in 9273c3a.
