### ISSUE TITLE
Missing tint2-executors folder in $HOME

### ISSUE THREAD

**Issue by PrismaPhonic** [Axarva/dotfiles-2.0#31]
On a recent install on a fresh system, if I pull up `tint2conf` and go down to the `executor 1`, `executor 2` etc. sections, I find taht the commands are looking for a folder in $HOME called `tint2-exectors` that does not exist.

**Comment by Axarva** [comment]
I believe these executors have nothing to do with how the bars are currently running. These are there probably due to my experiments while preparing these dotfiles and are safe to be ignored. Please do inform me if these cause any further issues.

**Comment by Axarva** [comment]
I suppose there were no further problems. Closing. Please do comment if anything else happens!
