### ISSUE TITLE
Remove Xmonad

### ISSUE THREAD

**Issue by Putnug1122** [Axarva/dotfiles-2.0#34]
How to  completely remove the entire xmonad things, cause it's kinda messed up my bspwm 😁

**Comment by Axarva** [comment]
Firstly, remove the config files. If you had older config files for any of the programs that this setup contains, move them back to the place they should be in. You should look into the install script that you used to install this setup to find out what config files were modified. That should make your older configurations come back.

Next, I assume that you're using Arch. Look into `install-on-arch.sh` and see the packages that were installed by the script. Uninstall them, and you should be fine. Lastly, for the sake of completeness, reboot your machine.

**Comment by Axarva** [comment]
Assuming everything worked, I’ll be closing this.
