### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by domogami** [Axarva/dotfiles-2.0#35]
I have just installed this beautiful theme on my XPS 15 flawlessly and I am extremely impressed! However, I cannot use anything because of the improper scaling of the 4k display. I am not sure if there is a way for everything to scale properly or what I can do to resolve this. Does Dotfiles-2.0 support scale factors?

**Comment by Axarva** [comment]
I am sorry for this inconvenience, but this issue will take quite a while to fix. The 2 resolutions that I initially planned to support were 1920x1080 and 1366x768, while your pc has 3840x2400. You could play around with tint2conf and ~/.config/eww to make it look a bit better, I’m afraid to tell you it’s not exactly what you’d call scalable, but if you use a little coordinate geometry and increase font sizes, it’d most likely work. Once again, I’m sorry for this inconvenience.

**Comment by domogami** [comment]
I was actually able to make it look great by setting the scale_relative_to_DPI to 282 and the scale_relative_to_screen_height to 1080! It looks flawless now and I absolutely love it! I also changed Xmonad to have a better DPI by modifying the .Xresources file and the xmonad.hs config file. I'm pretty happy with how everything turned out with just a few modifications! Thank you so much for your hard work on this!!

**Comment by Axarva** [comment]
That’s great! I’ll close this then, and refer anyone who has issues to have a look at this issue in the future. Thank you for taking your time for tinkering and coming up with a solution.
