### ISSUE TITLE
Got stuck on a "script"

### ISSUE THREAD

**Issue by MakeGamer** [Axarva/dotfiles-2.0#36]
After following "./install-on-arch.sh" it just got stuck on this script, here a video of it https://streamable.com/h27oev. I am not competent enough to do anything else or to fix it on my own so advice would be pretty cool :)

**Additional info:**
 - OS: Archlinux 2021.05.01
 - VM: Virtualbox

**Comment by Axarva** [comment]
That’s just paru opening a PKGBUILD for your inspection. Hit q on your keyboard to exit out of that. Also, keep in mind that this setup will most likely NOT work on a VirtualMachine. Good luck!

**Comment by MakeGamer** [comment]
> 
> 
> That’s just paru opening a PKGBUILD for your inspection. Hit q on your keyboard to exit out of that. Also, keep in mind that this setup will most likely NOT work on a VirtualMachine. Good luck!

Firstly thank you for your quick answer! And sadly you were right.
![grafik](https://user-images.githubusercontent.com/65780653/118359677-df347680-b584-11eb-821d-6e0ab676d63c.png)
it failed on building rofi.

**Comment by Axarva** [comment]
No, that’s not due to the issue of the VM. Run the script again for this case. This is more of a rofi issue than a VM one.

**Comment by MakeGamer** [comment]
I ran the script 5 times but I doesn't want to work. I also tried to install rofi on my own but probably totaly wrong.

**Comment by Axarva** [comment]
Hmm, is there a premade binary? That could be used in this case then.

**Comment by Axarva** [comment]
Also, could you show more error logs? I could be able to pinpoint the issue then.

**Comment by MakeGamer** [comment]
sure just a sec

**Comment by MakeGamer** [comment]
Here. I did it in [Normal speed](https://streamable.com/hwipvg) and in [0.5 speed](https://streamable.com/x5dy2s)

**Comment by Axarva** [comment]
Seems like you already have a different version of rofi installed. Please issue “sudo pacman -Rncs rofi” and re-execute the script.

**Comment by MakeGamer** [comment]
My videos corrupted :C Should I send correct versions again?

**Comment by MakeGamer** [comment]
> 
> 
> Seems like you already have a different version of rofi installed. Please issue “sudo pacman -Rncs rofi” and re-execute the script.

I'll try asap

**Comment by MakeGamer** [comment]
Same error https://streamable.com/qbaf8j

**Comment by Axarva** [comment]
![2521C69C-7681-4513-8192-52CD4E5ABC31](https://user-images.githubusercontent.com/66304313/118383785-e4df9a00-b620-11eb-8161-bfd030a3ad4f.jpeg)

This is something that you’ll have to ask in davatorium/rofi. I’m sorry but I cannot be of further help.

**Comment by MakeGamer** [comment]
ok no problem. Thank you tho for answering at all and try to help :)
