### ISSUE TITLE
I'm an absolute noob and I need help changing name and stuff in the Ctrl+P dashboard

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [Axarva/dotfiles-2.0#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rohit-Rangaraj** [comment]
Sorry DUPLICATE

**Comment by Axarva** [comment]
Is this solved now?
