### ISSUE TITLE
Change stuff in the Ctrl+P dashboard and workspaces taskbar

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [Axarva/dotfiles-2.0#38]
The title basically explains it
I need help changing the name and icons in the dashboard
And the icons on the workspaces taskbar seem irrelevant for my use, so I'd like to change it

PS: If u provided ways to change this, I'm really sorry, I looked up as much as possible

Thanks for making such an amazing config for xmonad.

**Comment by Axarva** [comment]
Oh, here’s the issue. I was a bit confused. These all are set in the ~/.config/eww.xml

**Comment by Axarva** [comment]
As for the workspace taskbar, open up your ~/.xmonad/xmonad.hs file. In an array, you will find a bunch of numbers with backslashes in front of them. Change those to simple numbers without the backslashes and save the file. Issue “xmonad - -recompile” and “xmonad - -restart”. Hit “Win + B” twice to see your changes.

**Comment by Rohit-Rangaraj** [comment]
Thanks a lot it works now!
