### ISSUE TITLE
How to get same look for firefox as shown in screenshot?

### ISSUE THREAD

**Issue by chiragasawa** [Axarva/dotfiles-2.0#39]
how to remove tab and search bar for firefox and custom home page.

**Comment by Axarva** [comment]
The specific instructions are on [this repo](https://github.com/dbuxy218/Prismatic-Night#Firefoxtheme). The startpages I use are just a modified version of this. Follow these instructions. For the `startpage/` directory it mentions, use the startpage directory provided in this repository. You will find all other necessary files there. That's for the start page.

The theme is MaterialFox. You can get it from [here](https://github.com/muckSponge/MaterialFox).

**Comment by Axarva** [comment]
Issue getting old. I'll close this for now since I specified the exact steps. Do comment again on this and I'll reopen.

**Comment by CyberBishop** [comment]
hey material fox says

> Linux is no longer officially supported but you can give it a try – if you'd like to work on it

and also when I use it like that my tab just keeps shaking till I delete the chrome file and restart my firefox
