### ISSUE TITLE
Greenclip

### ISSUE THREAD

**Issue by DrunkenMastah** [Axarva/dotfiles-2.0#42]
It's not something important but you don't mention anywhere the dependancy  greenclip even though you start a deamon at startup.I guess you can add `yay install rofi-greenclip` on startup script .Also it would be super cool to explain a bit what it does that xclip doesn't

**Comment by Axarva** [comment]
Hmm, `Super + Shift + A` triggers a rofi menu where you can see your clipboard selections. I use greenclip for that. If you do not want to use it, not installing it is fine. I'll add this as a dependency. Thank you!

**Comment by Axarva** [comment]
Will be closing this as greenclip is now listed as a dependency.
