### ISSUE TITLE
Script fails to build rofi

### ISSUE THREAD

**Issue by ALexus1907** [Axarva/dotfiles-2.0#45]
**Describe the bug**
"Packages failed to build: rofi-git-1.5.2.r102.g151547a9-1" appears when trying to install rofi via arch installation script

**To Reproduce**
Run the installation script and proceed normally up until rofi installation

**Expected behavior**
rofi installs normally and the script continues with the installation

**Desktop :**
 - OS: Arch

**Comment by abhigyan2001** [comment]
Same issue

**Comment by mlucap** [comment]
The way I fixed this was to

1. `cd ~`
2. `git clone https://aur.archlinux.org/rofi-git.git && cd rofi-git`
2. `makepkg -Acs`
3. Then you can run the script again: `cd ~/dotfiles-2.0 && ./install-on-arch.sh`
3. At first, I encountered 2 more "packages failed to build" but after running the script again they seemed to have fixed themselves

**Comment by Kellegram** [comment]
It's an issue with the rofi-git package, shoulda auto-resolve with time, but you don't even need rofi-git, just get rofi with pacman, I tested everything with it and there is no difference.

**Comment by Axarva** [comment]
Should work now since rofi is installed from pacman rather than rofi-git. Will be closing for now.
