### ISSUE TITLE
How to remove the bottom bar and let xmonad take full screen space?

### ISSUE THREAD

**Issue by system32uwu** [Axarva/dotfiles-2.0#48]
Not really a bug, but I tried changing values in ./xmonad/xmonad.hs and reloading xmonad (WIN+Q) and it doesn't change, is it something to do with eww? Also, is there any way to make the current window go fullscreen? Like, taking full width and height and rendering on top of the top bars. 

Using tint2conf I got rid of the bottom bar, but the height it took is still taking space:

I also notice some overlapping in the items of the top right bar, I checked previous issues and apparently it had something to do with the font, but I already have it installed.

My resolution is 1920 x 1080.

**Comment by Kellegram** [comment]
Axarva is manually setting gaps and padding, because with the current config, Xmonad has no idea that tint2 is there, or at least has no idea of its dimensions, so toggleStruts does not work. You need to edit xmonad.hs to remove the bottom padding. 

```hs
layoutHook = gaps [(L,30), (R,30), (U,40), (D,60)] $ spacingRaw True (Border 10 10 10 10) True (Border 10 10 10 10) True $ smartBorders $ myLayout,
```

**Comment by Axarva** [comment]
`Super + Ctrl + G` to toggle the gaps for now. Switch around the layout until you get to the fullscreen mode. As @Kellegram says, I currently set manual gaps and padding, hence I included something for toggling the gaps.

**Comment by system32uwu** [comment]
> 
> 
> Axarva is manually setting gaps and padding, because with the current config, Xmonad has no idea that tint2 is there, or at least has no idea of its dimensions, so toggleStruts does not work. You need to edit xmonad.hs to remove the bottom padding.
> Edit this line until it looks like you want it, although I am working on a way to make struts work so this is hopefully not necessary eventually:
> 
> ```haskell
> layoutHook = gaps [(L,30), (R,30), (U,40), (D,60)] $ spacingRaw True (Border 10 10 10 10) True (Border 10 10 10 10) True $ smartBorders $ myLayout,
> ```

Hello, I tried setting (D,0), and ...(Border 10 0 10 10), but as I said it's not updating, I haven't tried to restart though, but from my understanding reloading the configuration with WIN + Q should be enough for it to take effect.

**Comment by system32uwu** [comment]
> 
> 
> `Super + Ctrl + G` to toggle the gaps for now. Switch around the layout until you get to the fullscreen mode. As @Kellegram says, I currently set manual gaps and padding, hence I included something for toggling the gaps.

Yeah I know that pressing WIN + Space I can change the layout until I get the "fullscreen one", but with fullscreen I'm talking about **fullscreen** (the window taking the entire screen bounds, and rendering on top of everything else).

**Comment by system32uwu** [comment]
> `Super + Ctrl + G` to toggle the gaps for now. Switch around the layout until you get to the fullscreen mode. As @Kellegram says, I currently set manual gaps and padding, hence I included something for toggling the gaps.

Oh okay my bad, pressing Super + Ctrl + G toggles fullscreen for the active window, thank you

**Comment by system32uwu** [comment]
Okay I decided to get rid of the top bars so I'm going to close, thank you for your time guys.
