### ISSUE TITLE
Terminal showing errors when opened.

### ISSUE THREAD

**Issue by aleemont** [Axarva/dotfiles-2.0#5]
Alacritty logs:

`[2021-01-01 18:37:34.559364470] [ERROR] [alacritty_config] Problem with config: 
unknown variant "Subtract", expected one of "Key1", "Key2", "Key3", "Key4", 
"Key5", "Key6", "Key7", "Key8", "Key9", "Key0", "A", "B", "C", "D", "E", "F", 
"G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", 
"W", "X", "Y", "Z", "Escape", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", 
"F9", "F10", "F11", "F12", "F13", "F14", "F15", "F16", "F17", "F18", "F19", 
"F20", "F21", "F22", "F23", "F24", "Snapshot", "Scroll", "Pause", "Insert", 
"Home", "Delete", "End", "PageDown", "PageUp", "Left", "Up", "Right", "Down", 
"Back", "Return", "Space", "Compose", "Caret", "Numlock", "Numpad0", "Numpad1", 
"Numpad2", "Numpad3", "Numpad4", "Numpad5", "Numpad6", "Numpad7", "Numpad8", 
"Numpad9", "NumpadAdd", "NumpadDivide", "NumpadDecimal", "NumpadComma", 
"NumpadEnter", "NumpadEquals", "NumpadMultiply", "NumpadSubtract", "AbntC1", 
"AbntC2", "Apostrophe", "Apps", "Asterisk", "At", "Ax", "Backslash", "Calculator",
"Capital", "Colon", "Comma", "Convert", "Equals", "Grave", "Kana", "Kanji", 
"LAlt", "LBracket", "LControl", "LShift", "LWin", "Mail", "MediaSelect", 
"MediaStop", "Minus", "Mute", "MyComputer", "NavigateForward", "NavigateBackward",
"NextTrack", "NoConvert", "OEM102", "Period", "PlayPause", "Plus", "Power", 
"PrevTrack", "RAlt", "RBracket", "RControl", "RShift", "RWin", "Semicolon", 
"Slash", "Sleep", "Stop", "Sysrq", "Tab", "Underline", "Unlabeled", "VolumeDown",
"VolumeUp", "Wake", "WebBack", "WebFavorites", "WebForward", "WebHome", "WebRefresh",
"WebSearch", "WebStop", "Yen", "Copy", "Paste", "Cut"; ignoring binding`

and:
`
[2021-01-01 18:37:30.757172608] [ERROR] [alacritty_config] Problem with config: 
unknown variant "Subtract", expected one of "Key1", "Key2", "Key3", "Key4", "Key5",
 "Key6", "Key7", "Key8", "Key9", "Key0", "A", "B", "C", "D", "E", "F", "G", "H",
"I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X",
"Y", "Z", "Escape", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10",
"F11", "F12", "F13", "F14", "F15", "F16", "F17", "F18", "F19", "F20", "F21", 
"F22", "F23", "F24", "Snapshot", "Scroll", "Pause", "Insert", "Home", "Delete", 
"End", "PageDown", "PageUp", "Left", "Up", "Right", "Down", "Back", "Return", 
"Space", "Compose", "Caret", "Numlock", "Numpad0", "Numpad1", "Numpad2", 
"Numpad3", "Numpad4", "Numpad5", "Numpad6", "Numpad7", "Numpad8", "Numpad9", 
"NumpadAdd", "NumpadDivide", "NumpadDecimal", "NumpadComma", "NumpadEnter", 
"NumpadEquals", "NumpadMultiply", "NumpadSubtract", "AbntC1", "AbntC2", 
"Apostrophe", "Apps", "Asterisk", "At", "Ax", "Backslash", "Calculator", "Capital",
"Colon", "Comma", "Convert", "Equals", "Grave", "Kana", "Kanji", "LAlt", "LBracket", 
"LControl", "LShift", "LWin", "Mail", "MediaSelect", "MediaStop", "Minus", "Mute", 
"MyComputer", "NavigateForward", "NavigateBackward", "NextTrack", "NoConvert", 
"OEM102", "Period", "PlayPause", "Plus", "Power", "PrevTrack", "RAlt", "RBracket", 
"RControl", "RShift", "RWin", "Semicolon", "Slash", "Sleep", "Stop", "Sysrq", "Tab", 
"Underline", "Unlabeled", "VolumeDown", "VolumeUp", "Wake", "WebBack", "WebFavorites", 
"WebForward", "WebHome", "WebRefresh", "WebSearch", "WebStop", "Yen", "Copy", 
"Paste", "Cut"; ignoring binding
`

**Comment by Axarva** [comment]
I remember this one, could you copy the alacritty.yml.arch file to your ~/.config/alacritty.yml? That will fix this.

**Comment by SoreqDH** [comment]
update your Add and Subtract keys to NumpadAdd/NumpadSubtract (https://github.com/alacritty/alacritty/issues/4506).
It fixed it for me.

**Comment by aleemont** [comment]
Fixed for me too. Closing issue.

**Comment by Axarva** [comment]
> update your Add and Subtract keys to NumpadAdd/NumpadSubtract ([alacritty/alacritty#4506](https://github.com/alacritty/alacritty/issues/4506)).
> It fixed it for me.

This is the way to fix it as in the referenced issue, but currently I use an older version of alacritty that exists as the latest stable in the gentoo repositories. Hence, an alacritty.yml specifically modified for later versions is present as alacritty.yml.arch, as well as the original configurations.
