### ISSUE TITLE
How to make xmonad take up lesser space on the bottom

### ISSUE THREAD

**Issue by meehirmanitrips** [Axarva/dotfiles-2.0#54]
This not a bug but a question.
I have disabled the dock at the bottom using tint2( I just removed the launcher from the panel and then set it to auto hide) but i can't make xmonad cover the gap left after removing the dock( it looks weird so i want to extend it to the bottom of my screen with very less spacing)
But when i edit the config file in ~/.xmonad/xmonad.hs

`layoutHook = gaps [(L,30), (R,30), (U,40), (D,60)] $ spacingRaw True (Border 10 10 10 10) True (Border 10 10 10 10) True $ smartBorders $ myLayout,
`
and setting the D value to something lesser it just doesn't work.

Can someone help me out with this(I am new to this stuff)

**Comment by Axarva** [comment]
After setting the D value, you need to issue `xmonad --recompile` and `xmonad --restart`.

**Comment by meehirmanitrips** [comment]
> After setting the D value, you need to issue `xmonad --recompile` and `xmonad --restart`.

I've already tried that and it still doesn't work.
Do i need to change anything in the border section too?
I can't figure out why it's acting this way

**Comment by Kellegram** [comment]
> > After setting the D value, you need to issue `xmonad --recompile` and `xmonad --restart`.
> 
> I've already tried that and it still doesn't work.
> Do i need to change anything in the border section too?
> I can't figure out why it's acting this way

Did you see if it's the same way after relog? Certain changes to xmonad do not refresh unless you do modkey + shift + space or re-log.

**Comment by meehirmanitrips** [comment]
> > > After setting the D value, you need to issue `xmonad --recompile` and `xmonad --restart`.
> > 
> > 
> > I've already tried that and it still doesn't work.
> > Do i need to change anything in the border section too?
> > I can't figure out why it's acting this way
> 
> Did you see if it's the same way after relog? Certain changes to xmonad do not refresh unless you do modkey + shift + space or re-log.
Got it....Thank you so much for the help.

**Comment by meehirmanitrips** [comment]
> > > After setting the D value, you need to issue `xmonad --recompile` and `xmonad --restart`.
> > 
> > 
> > I've already tried that and it still doesn't work.
> > Do i need to change anything in the border section too?
> > I can't figure out why it's acting this way
> 
> Did you see if it's the same way after relog? Certain changes to xmonad do not refresh unless you do modkey + shift + space or re-log.

Got it......thank you so much for the help.

**Comment by Kellegram** [comment]
@meehirmanitrips Was it the re-log or the button combo that fixed it?

(FYI, changes to colors and stuff also often apply only after the button combo, this button combo also needs to be used per-workspace I believe, but there might be one that works on them all, that's something I would need to check).

**Comment by meehirmanitrips** [comment]
> @meehirmanitrips Was it the re-log or the button combo that fixed it?
> 
> (FYI, changes to colors and stuff also often apply only after the button combo, this button combo also needs to be used per-workspace I believe, but there might be one that works on them all, that's something I would need to check).

It was the button combo.......I pressed the mod+G  and its now working fine.
Thanks again :)
