### ISSUE TITLE
How to open Notifications 

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [Axarva/dotfiles-2.0#56]
When the notifications come up in the top right, a click just dismisses the notification, how do I click on it to redirect me to that actual page?

**Comment by Kellegram** [comment]
> When the notifications come up in the top right, a click just dismisses the notification, how do I click on it to redirect me to that actual page?

I don't think dunst supports something like that @Rohit-Rangaraj. Maybe if you scripted it? You can take a look at this page (https://github.com/dunst-project/dunst/blob/3f3082efb3724dcd369de78dc94d41190d089acf/dunstrc#L237) but dunst is pretty minimal.

**Comment by Rohit-Rangaraj** [comment]
I just looked at the dunst config file and it had mapped the middle mouse button for redirection. So dunst does support that and I didn't know that

**Comment by Rohit-Rangaraj** [comment]
But now the issue is solved and for anyone struggling please check `~/.config/dunst/dunstrc`

**Comment by Kellegram** [comment]
@Rohit-Rangaraj I tried that in the past coz I have seen the comment in dunstrc, but it has never worked for me, did it actually work for you?

**Comment by Rohit-Rangaraj** [comment]
Yes it did work for me. I'll send u the snippet one minute

**Comment by Rohit-Rangaraj** [comment]
![2021-06-04-20:59:03-screenshot](https://user-images.githubusercontent.com/20149534/120826313-ea713580-c577-11eb-93be-3113f3f8f77f.png)

**Comment by Rohit-Rangaraj** [comment]
See if this works for you.

**Comment by Kellegram** [comment]
> See if this works for you.

Nope, it does not. Perhaps I am missing something in my session. I guess I need to investigate this further and see if I can get it working for me. Thanks though.

**Comment by Rohit-Rangaraj** [comment]
No probs
