### ISSUE TITLE
Image in profile widget?

### ISSUE THREAD

**Issue by onlyvip** [Axarva/dotfiles-2.0#59]
I am unable to get the proper syntax in order to get the Avatar image get shown in the profile eww widget, can you show me what line should i use in the eww.xml file under profile?
![image](https://i.imgur.com/Mkmk9BK.png)
heres what i have tried to do in eww.xml
https://termbin.com/ojzc
^ line 136 i dont know whats wrong in there
And secondly how do I get mpd instead of Spotify in sidebar music widget?

**Comment by Axarva** [comment]
The image is set in `eww.scss` at line 346. Please undo the changes you made to `eww.scss` when figuring this out.

As for mpd instead of Spotify, making mpd follow the MPRIS specifications through mpDris2 or any other plugin should get the interface running.

If your local song files have album art attached to them, the process to get those is a bit long, and I won't go through it unless you do require them.

**Comment by onlyvip** [comment]
> The image is set in `eww.scss` at line 346. Please undo the changes you made to `eww.scss` when figuring this out.
> 
> As for mpd instead of Spotify, making mpd follow the MPRIS specifications through mpDris2 or any other plugin should get the interface running.
> 
> If your local song files have album art attached to them, the process to get those is a bit long, and I won't go through it unless you do require them.

Ok I check line 346 after undoing. Thanks. Can you share your CSS file where you have set the profile pic?
About mpd I don't use Spotify. I only use mpd with albumart embedded so yeah I need it actually. If you can implement it then I would love that. Thanks again. Love the widgets btw they are dope.

**Comment by Axarva** [comment]
Installing mpDris2 should do the trick actually. 

By line 346, I meant line 346 in your eww.scss. 
Set the path there as /home/{your-user}/path/to/image.png

**Comment by Axarva** [comment]
![image](https://user-images.githubusercontent.com/66304313/122666607-11fa0c00-d1ce-11eb-8dde-894f83efae60.png)
Here's the specific line.

**Comment by Axarva** [comment]
I'll assume that it got fixed. Please comment and I'll reopen the issue.
