### ISSUE TITLE
Icons looking broken/buggy.

### ISSUE THREAD

**Issue by aleemont** [Axarva/dotfiles-2.0#6]
Why does icons look like this?

![image](https://user-images.githubusercontent.com/64771662/103444351-ea3ada00-4c67-11eb-8aa3-a6ee5d1ff102.png)
![image](https://user-images.githubusercontent.com/64771662/103444369-0d658980-4c68-11eb-9ed6-406f71078bb5.png)

And here: even if I made the changes to panellauncher.tint2rc nothing changed.
![image](https://user-images.githubusercontent.com/64771662/103444374-135b6a80-4c68-11eb-9cac-7b043917f129.png)

I noticed I can't logout too even if I changed the eww scripts as you described in `README.md`.

In the end, weather is not working properly. 

(sorry for opening so many issues, but I'm discovering stuff step by step)

**Comment by aleemont** [comment]
I tried to install candy-icons again, and I tried with candy-icons-git as well, but I had no luck tho

**Comment by aleemont** [comment]
Fixed.

**Comment by aleemont** [comment]
Last part fixed, had to reduce a little bar size.

**Comment by Axarva** [comment]
This is a font issue. Do you have the Museo Sans ttf file mentioned in the readme? If you do, try issuing “fc-cache -f”. Additionally, the Nerd fonts present in the fonts directory would also be necessary. If the changes do not take place immediately, try re-logging in to xmonad.

**Comment by Axarva** [comment]
The weather scripts I provide seem to be working fine, if they weren’t working, you wouldn’t be seeing that message. Please make sure the variables in the getweather script are correct. Try debugging with stuff like adding “echo $weather” to the getweather script. Be sure to remove the echo line after the debugging process.

**Comment by Axarva** [comment]
Is it just the logout not working? Are the locksceeen, reboot, and shutdown buttons working? I need a bit more information on this.

If its just the logout button, could you tell me what are you using to start xmonad? (As in a display manager or xinit) 

If you are using a display manager, could you send me the contents of the file /etc/X11/Sessions/xmonad ? This file’s location may be different on your system so if the file doesn’t exist, I’ll get back to you soon.

**Comment by Axarva** [comment]
And lastly, for the profile picture, replace the image path given in the eww.scss (given as: ~/.config/eww/images/pengus-hi.png) to something that points to the path from the root directory: 
Something like this will load the image:
/home/{your_user}/path/to/image.png

**Comment by aleemont** [comment]
I can confirm that only logout is not working. Shutdown and reboot are working.
I still can't figure out how to fix weather and font in the menu. I'm pretty sure I have the font installed, but I may be wrong. Can you post the Museo Sans font file please? 
What do you mean with "what do you use to start xmonad"?
Like Lightdm maybe?

**Comment by Axarva** [comment]
If you are using LightDM, could you check if your `/etc/X11/xsessions/xmonad` flie looks like this?
![image](https://user-images.githubusercontent.com/66304313/103449999-227a0100-4cd8-11eb-83c6-75ad884b153e.png)

Or does it look like this?
![image](https://user-images.githubusercontent.com/66304313/103450052-e8f5c580-4cd8-11eb-87c7-466a7b15013e.png)

If it looks like the second one, that would explain why xmonad doesn't exit. I suggest you to try this command then:
```bash
loginctl terminate-session $(loginctl session-status | head -n 1 | awk '{print $1}')
```

**Comment by Axarva** [comment]
For the font, now that I researched it a bit more, perhaps the 500 weight ttf can be provided for desktop purposes. I might add it soon, but for the time being Googling `Museo Sans ttf` should lead you to multiple websites that provide the font.

**Comment by aleemont** [comment]
Weather is now working, I made a typo in my API key. 
I've been able to change my avatar icon and username, but I couldn't fix the font issues (maybe it is related to Iosevka and not to Museo Sans(?)) Or probably I did something wrong while I installed the font.

I fixed some little problems with the upper panels: In the system tray you had a battery module which wasn't showing so I deleted some Executors and resized the panel;
I noticed that when I disconnected the AC adapter the Battery module used to show remaining life-time (I guess??) on a second line, so I set Second Line Font size = 0 and solved the issue. 
I made icons bigger in all upper panels too. I centered clock as well, adding seconds, removing padding and reducing font size to 9.
The lower panel had problems displaying icons, I reduced its size by 1 pixel and this is now looking good.

**Comment by Axarva** [comment]
Great! The panel lengths are specified with percentages so I was pretty sure everyone would face these issues, hence I actually recommended to use `tint2conf` to edit them. 

Hmm, I provide most of the fonts already in the repo. I'll add in Museo Sans as well then.

**Comment by Axarva** [comment]
As for the icons I tried installing in a vm and I can confirm that it looks broken:

![image](https://user-images.githubusercontent.com/66304313/103450540-31fd4800-4ce0-11eb-84b0-18bb573ac51e.png)

(Don't mind the date)

I fixed this with the following:
- Copying everything in the fonts directory of this repo to `~/.local/share/fonts` like this:
```bash
cd dotfiles-2.0/fonts
cp * ~/.local/share/fonts/
```
- Next, I got Museo Sans, unzipped the file, and put the resulting files in `~/.local/share/fonts` as well.

This produced what looks like this:

![image](https://user-images.githubusercontent.com/66304313/103450598-fadb6680-4ce0-11eb-9211-b969826b4199.png)
You can see that all the weird buttons are gone.
Could you try this out?

**Comment by Prastab** [comment]
I can confirm this is a font issue as well. When I installed it at first it looked ugly like that, but after installing the Museo Sans font the issue was solved.

**Comment by aleemont** [comment]
Can you provide me the link where you found the font please? Maybe I'm doing something wrong

**Comment by Axarva** [comment]
https://www.fontshmonts.com/text-fonts/museo-sans/
I believe it was from here, I own the 300 weight font, which is licensed. This means I cannot upload the file to the repository sadly.
I might have to edit the link from the comment as well.
For further on this one, it would be best to ask me for this on Discord or other such places.

**Comment by aleemont** [comment]
> For further on this one, it would be best to ask me for this on Discord or other such places.
Okay. will you give me your username for Discord? I'm sorry for bothering you in such this way but I love your theme and colorscheme

**Comment by Axarva** [comment]
No, I meant the discord part just for the fonts. The issues here are going well, and could serve as references for anyone who has problems that you face as well. :) 
So I recommend you keep opening newer issues!

I’m on the r/unixporn discord server and my username is “Eh?Okay...#8545“

(I know. Kinda weird :D)

**Comment by aleemont** [comment]
> No, I meant the discord part just for the fonts. The issues here are going well, and could serve as references for anyone who has problems that you face as well. :)
> So I recommend you keep opening newer issues!
> 
> I’m on the r/unixporn discord server and my username is “Eh?Okay...#8545“
> 
> (I know. Kinda weird :D)

I was, obviously referring to the font. I will get into the r/unixporn server tho. Thx

**Comment by aleemont** [comment]
We finally find a solution:
1. Download Museo Sans 300 from anywhere you want
2. Put the `MuseoSans-300.otf` or `MuseoSans-300.ttf` in `~/.local/share/fonts`
3. Run `fc-cache -f `
5. Open `~/.config/eww/eww.scss` in any text editor you want and add 
`* {
  all:unset; 
}` 
at the top of the file
6. Reboot

**Comment by Axarva** [comment]
Implemented final fix addressing buttons for 1366x768 screen in d605718

**Comment by yoge67855** [comment]
nothing works

**Comment by yoge67855** [comment]
>eww logs
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
[src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string

**Comment by Ferryistaken** [comment]
> > eww logs
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string
> > [src/eww_state.rs:35] Error while updating UI based after state change: couldn't convert "" to f64: cannot parse float from empty string

Same problem on Arch

**Comment by Axarva** [comment]
@Ferryistaken 
This issue is a different one. For tracking purposes (which means to make it a bit easier to keep track of issues, please open a new issue.

**Comment by system32uwu** [comment]
How did you guys got the profile picture showing? I edited the image path in eww.scss, but nothing is showing
