### ISSUE TITLE
Trouble configuring the Mod + P menu

### ISSUE THREAD

**Issue by Wojnstup** [Axarva/dotfiles-2.0#60]
I have trouble getting the changes I made in the ~/.config/eww/eww.xml file to work. This is what I changed:

![Untitledasdasd](https://user-images.githubusercontent.com/78437858/122669323-4c52b180-d1ac-11eb-9976-7f01ebe20f87.png)

What do I have to do to apply this changes? I've already recompiled and restarted xmonad.
EDIT: I also tried to edit the eww.scss file but to no effect.

![1231231231231](https://user-images.githubusercontent.com/78437858/122669427-cd11ad80-d1ac-11eb-887c-b6136ee79749.png)

**Comment by Axarva** [comment]
`eww.scss` doesn't support specifying the path with `~/path`
Please replace `~` with `/home/{your_user_here}`.

**Comment by Axarva** [comment]
You should also reverse the changes to `eww.xml` because, well, all you need to do to set your profile picture is modify `eww.scss`.

**Comment by Wojnstup** [comment]
Changing the path fixed it, thanks!

**Comment by Axarva** [comment]
Alright, closing.
