### ISSUE TITLE
Hey i wanna reinstall it

### ISSUE THREAD

**Issue by Aadi775** [Axarva/dotfiles-2.0#61]
how can i reinstall it

**Comment by Axarva** [comment]
In case your previous install was unsuccessful, just rerun the script.

In case you removed the setup and installed a new one, just rerun the script.

In case your previous installation was successful but stuff didn't work well, rerun the script. 

Basically, rerun the script.

**Comment by Axarva** [comment]
Also, please use the latest version of the repo as it contains fixes for long-standing bugs.

**Comment by Axarva** [comment]
Closing, please comment again if you have any issues.
