### ISSUE TITLE
Cant open the sidebar or dashboard

### ISSUE THREAD

**Issue by Teckmek** [Axarva/dotfiles-2.0#63]
I installed this config yesterday and it was working fine.
Today i turned on my pc and tried to open the sidebar with window+s but nothing happened so i tried to do win+p but nothing happened either.
What should i do to fix this?

**Comment by Teckmek** [comment]
i manged to fix it be switching to the main branch from the modified branch

**Comment by Axarva** [comment]
That's... weird, I'll keep this reopen until I figure out what is wrong with `modified`.

**Comment by Axarva** [comment]
I didn't find a single difference between the two branches that could be causing you such issues. There was a wayward `zsh` shebang, and I just fixed that. Are you sure it wasn't just a broken install which got fixed after you reinstalled?

**Comment by Teckmek** [comment]
I tried using the modified branch again and it worked. I dont know what was wrong but im happy it works now.
