### ISSUE TITLE
No rounded corners

### ISSUE THREAD

**Issue by Teckmek** [Axarva/dotfiles-2.0#64]
My dock has squared corners,the sidebar does and when i do win+p the screeen goes blank.
Im on arch linux.

**Comment by Axarva** [comment]
This is a compositor issue. Make sure you're using `picom-jonaburg` and use the configuration file provided in the repo.

**Comment by Axarva** [comment]
@Teckmek was this issue resolved?

**Comment by Teckmek** [comment]
No

**Comment by Axarva** [comment]
Does picom produce any logs?

**Comment by Axarva** [comment]
Closing. Make sure your picom configs are correct, picom is running, and that everything is just as the readme suggests. If the issue persists, please comment again.

**Comment by Teckmek** [comment]
Sorry for the late response I’ve been busy so I didn’t rly have time to use GitHub, I will check the logs and configs tomorrow

**Comment by Axarva** [comment]
Great!

**Comment by Teckmek** [comment]
when i run the picom command it gives me this
[ 07/22/21 11:43:05.367 parse_kawase_blur_strength INFO ] blur-strength: 6 [.iter = 3, .offset = 3.500000, .expand = 50]
[ 07/22/21 11:43:05.377 session_init FATAL ERROR ] Another composite manager is already running

**Comment by Teckmek** [comment]
I also have compton on my pc, should I remove it?
when i run compton it gives me this[ 07/22/21 11:44:26.244 parse_kawase_blur_strength INFO ] blur-strength: 6 [.iter = 3, .offset = 3.500000, .expand = 50]
[ 07/22/21 11:44:26.244 session_init WARN ] This compositor has been renamed to "picom", the "compton" binary will not be installed in the future.
[ 07/22/21 11:44:26.261 session_init FATAL ERROR ] Another composite manager is already running

**Comment by Axarva** [comment]
Hmm, it seems there is another compositor already running. You'll have to check which one is running with `htop` or other utilities. Make sure `picom-jonaburg` is the only compositor running.

**Comment by Teckmek** [comment]
so when i run picom in the terminal it starts now as i made some edits to it, it gives me the rounded corners. But when i close the terminal with picom running it gives me squared corners again.

**Comment by Axarva** [comment]
That is because you close the terminal. Add the picom command you use to .xinitrc (or .xprofile if you use a DM), and reboot.

Either add the command there or check if your xmonad.hs already contains the command. If the xmonad file already contains the command, there is no need to add it to the other files. Reboot your machine.

**Comment by Teckmek** [comment]
Ok that fixed it. Thanks for the help. I have 1 more question. In some of the screenshots, the windows are resized, i have tried to resize the windows on my setup but i couldn't figure out how to, could you tell me how you resized the windows.

**Comment by Axarva** [comment]
Hold down your mod key and left click and drag your windows to move them.

Hold down your mod key and right click and drag on your windows to resize them.

**Comment by Teckmek** [comment]
ty for the help
