### ISSUE TITLE
Smoother Animations

### ISSUE THREAD

**Issue by Rohit-Rangaraj** [Axarva/dotfiles-2.0#65]
Umm, all the animations are now super snappy. It used to be smoother but I tinkered around the xmonad.hs file but can't seem to replicate it. Any ideas on how to? And btw by animations I mean switching between workspaces and toggling the bars and all that
Thanks in Advance!

**Comment by Axarva** [comment]
Could you look if your compositor is active? 

Also, can’t exactly understand snappy. Could you perhaps record a video and post it here?

**Comment by Rohit-Rangaraj** [comment]
My compositor (picom) is active.

https://user-images.githubusercontent.com/20149534/123683122-7883c780-d869-11eb-9b67-a9f3417fcce0.mp4

This is what I mean by very snappy it used to be much smoother.

**Comment by Axarva** [comment]
How do you start picom? Try starting it with `picom -f`


Could you also check if you're using picom-jonaburg?


And finally, could you check your picom.conf and compare it to this repo's sample?

**Comment by Rohit-Rangaraj** [comment]
I was starting it with picom -b but yeah -f works!

**Comment by Rohit-Rangaraj** [comment]
Thanks!
