### ISSUE TITLE
Dashboard looks wrong

### ISSUE THREAD

**Issue by Teckmek** [Axarva/dotfiles-2.0#66]
When i do win+p the weather widget is connect to the directorys and image thing.Any help would be nice.

**Comment by Teckmek** [comment]
![Screenshot from 2021-07-01 19-09-53](https://user-images.githubusercontent.com/67555457/124171326-51630b00-daa0-11eb-9759-1e23ff6ed24c.png)

**Comment by Teckmek** [comment]
also how do I get quotes to show up

**Comment by Axarva** [comment]
Did you resize the widgets? Also, seems like you don't have the required fonts.

The fix to this would be to go to `~/.config/eww/eww.scss` and change this font-size to a smaller value:

![image](https://user-images.githubusercontent.com/66304313/124219340-e3f4c000-db1b-11eb-8149-f30a78b96dfb.png)


To get the quotes to show up, edit your crontab and put in the lines as described in the readme. Replace `{Your_user}` with your username. 

An example crontab:

![image](https://user-images.githubusercontent.com/66304313/124219420-11da0480-db1c-11eb-8cee-65636ad5ffb2.png)

**Comment by Teckmek** [comment]
How do i edit the contrab. Sorry if thats a noob question but im new to linux.
