### ISSUE TITLE
Dude this thing doesn't load

### ISSUE THREAD

**Issue by MohneeshSharma** [Axarva/dotfiles-2.0#67]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Axarva** [comment]
Uhm, would you mind specifying what exactly doesn’t load?

**Comment by Axarva** [comment]
Closing, please specify the issue in case you have any. Will reopen then.

**Comment by MohneeshSharma** [comment]
Its actually not loading the beautiful setup when loaded up. only black screen. This is because during installation, when i'am about to enter "Paru is installed or not", it doesn't wait for my input. And I would really suggest using Yay package manager instead of Paru.
Thanks

**Comment by Axarva** [comment]
I don't think the script would just not wait for your input. I tried it myself just now, and it works like a breeze. Sure, I'll add the option to select the AUR helper of your choice soon.

**Comment by Axarva** [comment]
AUR helper choice added in  6bf4c64. Will be closing this. Please comment again if you have issues.
