### ISSUE TITLE
no startx by default on xmonad

### ISSUE THREAD

**Issue by cronos-hash** [Axarva/dotfiles-2.0#69]
Hello, im sorry if this issue is unrelated, i just finished installing these dotfiles on a fresh install with arch. supplied "exec xmonad" into the .xinitrc doesnt seem to be working despite startx working. everytime i login i have to enter startx, any idea why?

thank you

**Comment by cronos-hash** [comment]
also unsure why, but this may be effecting the picom & on startuphook with xmonad?

**Comment by Axarva** [comment]
> Hello, im sorry if this issue is unrelated, i just finished installing these dotfiles on a fresh install with arch. supplied "exec xmonad" into the .xinitrc doesnt seem to be working despite startx working. everytime i login i have to enter startx, any idea why?
> 
> thank you

I mean, isn't .xinitrc supposed to execute whatever is within it *after* startx is executed?

If you want the session to automatically start once you log in, I suggest using a display manager, or maybe including `startx` on your default shell (unsure about the second option, I've always used display managers).

**Comment by Axarva** [comment]
> also unsure why, but this may be effecting the picom & on startuphook with xmonad?

Highly unlikely, but it could be. I'd try using a display manager once to see if your issue is resolved.

**Comment by cronos-hash** [comment]
Which display manager would you recommned ?

**Comment by Axarva** [comment]
I personally use lightdm

**Comment by cronos-hash** [comment]
lightdm is the way
