### ISSUE TITLE
EWW weather script not working

### ISSUE THREAD

**Issue by SethPuhala** [Axarva/dotfiles-2.0#71]
I did as the config file told put in api key and city id but still same result. eww not showing any weather stats

**Comment by Axarva** [comment]
Are you sure they’re correct? Did you try executing the script manually?

**Comment by Shahab96** [comment]
Actually I have this issue as well, executing the script manually works perfectly fine however the dashboard doesn't show any info. This may or may not be a config issue on my end however, I'll look into it further and let you know.

**Comment by Axarva** [comment]
Could you show how the dashboard doesn't show anything?

**Comment by SethPuhala** [comment]
OK I found something I tried running the scripts in terminal and sure enough it works. so then i went to take a screenshot of the eww weather issue and weather was there. I reboot and try again without running script and back to no weather stats only works after manually running file. I could write a startup script to run getweather but maybe there is a fix i could make in the config files that would be better?

**Comment by Axarva** [comment]
I mean, that is literally why the readme mentions to edit your crontab.

**Comment by Axarva** [comment]
> ![image](https://user-images.githubusercontent.com/66304313/126193931-47f2237e-0f91-4df1-af0f-c20a0bc1de31.png)

Please go through the readme before considering opening up an issue. This is the related section.

Make sure `cron` is installed, and the service is enabled on your machine. (If on OpenRC, `rc-update add cron default`, if on systemd `systemctl enable cron.service`)

**Comment by SethPuhala** [comment]
yes i did that when i installed and double checked it now still no dice

**Comment by Axarva** [comment]
So the weather script doesn’t work with cron? Does it not even say “Weather not available”? 
Because if the script is ran, the fallback if anything goes wrong is that. If that does not appear on your screen, you need to look into your crontab again.

**Comment by redgloboli** [comment]
do you maybe have aliases on grep or cat? like batgrep or something similar? i do have and i had to replace grep with /usr/bin/grep in the scripts as the output couldn't be read correctly when using bat/batgrep.

**Comment by Shahab96** [comment]
Just to be sure, after putting in your api id and city id, did you also set a unit? (Metric/Imperial)

Mine also had an issue where it wasn't working but adding the metric was the problem, adding it fixed it for me.

**Comment by darshan315** [comment]
Hello,

Make sure you have initialized correct path in `./config/eww/scripts/getweather`. 
In case of example and details about **appid**, **id**, and **unit**, see [here.](https://openweathermap.org/appid).

Good luck!

**Comment by Eason0210** [comment]
I set ID="524901" and it work well.  But how can I get my City ID?  My City is Shangahi of China.

**Comment by Axarva** [comment]
Any updates here?

**Comment by ViiEx** [comment]
I did some searching cause I had the same problem. I think the api call is what the script doesn't like.

I changed mine to:

```shell
weather=$(curl -sf "https://api.openweathermap.org/data/2.5/weather?id=$ID&APPID=$KEY&units=$UNIT")
echo "$weather"
```

and it worked just fine.

**Comment by Axarva** [comment]
I'll be closing this since there have been no updates from the original author. Please comment again on the issue and I'll be happy to reopen :)
