### ISSUE TITLE
Cant install on fresh install of arch.

### ISSUE THREAD

**Issue by alexfeed1990** [Axarva/dotfiles-2.0#72]
Ive runned the ``install-on-arch.sh`` script around 3 times. since it failed. First time i ran it as root, second time i did a prompt wrong, the third time, it got to the end but no zsh installation. It closed at the XMonad recompiled thing.

**Comment by Axarva** [comment]
It ISN'T meant to be run as root. 

Show me how it exits when you execute it as a normal user.

**Comment by Shahab96** [comment]
Having the same issue here, did not run as root and the script did successfully complete however when I log in there’s no gui, I just get logged into my fish interface as usual

**Comment by Axarva** [comment]
Yep, you could use a dm, or you could use startx to log in. This setup just provides a *setup*, getting your xorg server to run is not a part of this repository.

**Comment by alexfeed1990** [comment]
Thanks for the help, i went on the trip of making XMonad my own since this piece of art couldnt run on my potato. i reinstalled arch and managed to install this. Ill make sure  to use this when i get a better pc! Thanks!
