### ISSUE TITLE
Installed but nothing is working 

### ISSUE THREAD

**Issue by Gray-Zero** [Axarva/dotfiles-2.0#75]
I have done everything it said in note.txt and when I gave it a restart nothing In arch is working 
![image](https://user-images.githubusercontent.com/62302371/126156377-a9155e19-c7a0-4911-9558-ecccbfa52453.jpg)

and I did the export bin thing In Bashrc

**Comment by Axarva** [comment]
Um, this looks like serious trouble. Are you sure you installed your distribution properly?

**Comment by Gray-Zero** [comment]
Yep i did it was working perfectly fine

**Comment by Axarva** [comment]
Could you show me your edits to your bashrc

**Comment by Gray-Zero** [comment]
I can't since I can't do cat or nano I can't do anything

**Comment by Gray-Zero** [comment]
Like I can reinstall it arch and try again ?

**Comment by Axarva** [comment]
No, that won't be necessary. Can you log in as root?

**Comment by Gray-Zero** [comment]
I will try in 5 mins

**Comment by Gray-Zero** [comment]
Ok I am now gonna log into root

**Comment by Gray-Zero** [comment]
Ok root works ls and everything works

**Comment by Gray-Zero** [comment]
Like the commands

**Comment by Axarva** [comment]
Edit your user's bashrc now and find the error.

**Comment by Axarva** [comment]
The commands to issue as root are most likely `vim /home/$YOUR_USER/.bashrc`.

**Comment by Gray-Zero** [comment]
This is my bashrc like nothing else is wrong

**Comment by Gray-Zero** [comment]
When I remove that bashrc like export bin thing it works the normal user

**Comment by Axarva** [comment]
Try moving the `export` line to the end of your file. I'm not sure what's causing the issue.

**Comment by Gray-Zero** [comment]
Btw what does it mean to make a .xinitrc like a blank file called that in my home directory

**Comment by Gray-Zero** [comment]
I put the export at the end but it's still the same problem

**Comment by Axarva** [comment]
Yes. In case you use a display manager such as lightdm, that is not necessary. If you plan to use the utility `startx`, it is necessary.

**Comment by Gray-Zero** [comment]
Oh ok

**Comment by Gray-Zero** [comment]
But any idea when I put the export same thing

**Comment by Axarva** [comment]
> I put the export at the end but it's still the same problem

Hmm, I am not sure at all what's causing the issue. Try changing the `'` in your export line to `"`. That's literally the only thing left that I can suggest.

**Comment by Gray-Zero** [comment]
Ok

**Comment by Gray-Zero** [comment]
No way so double quotes work

**Comment by Gray-Zero** [comment]
But when when I log in I am in tty

**Comment by Axarva** [comment]
Execute `startx`

**Comment by Gray-Zero** [comment]
I did But it gives me a big ton of error and I have the file .xintric thing

**Comment by Axarva** [comment]
Send the errors.

**Comment by Gray-Zero** [comment]
Here is the error ![image](https://user-images.githubusercontent.com/62302371/126165859-338389d4-857b-4c7c-967b-5cc4b84ea97a.jpeg)

**Comment by Axarva** [comment]
Try
`sudo chmod u+s /usr/bin/xinit`

**Comment by Gray-Zero** [comment]
I did that now and I gave my thing I a restart and now I did startx and get this ![image](https://user-images.githubusercontent.com/62302371/126168141-bf0f1762-e656-47c9-888f-8f822b1df9ab.jpeg)

**Comment by Axarva** [comment]
What groups is your user in? Check with `groups`

**Comment by Gray-Zero** [comment]
The group I am in wheel group

**Comment by Axarva** [comment]
Any other groups?

**Comment by Gray-Zero** [comment]
That's all

**Comment by Axarva** [comment]
Well, try this:
`sudo usermod -a -G video,audio namo`

**Comment by Axarva** [comment]
Log out, log in again, and try `startx`

**Comment by Gray-Zero** [comment]
Same error but the groups changed

**Comment by Axarva** [comment]
Did you check if your xorg configuration worked before you installed this setup?

**Comment by Gray-Zero** [comment]
Nope I did not check it

**Comment by Gray-Zero** [comment]
I did not have it installed the arch thing installed it for me

**Comment by Axarva** [comment]
Hm. This is purely an xorg setup issue then. Post the entire xorg log please.

**Comment by Gray-Zero** [comment]
![image](https://user-images.githubusercontent.com/62302371/126173349-2e11fbf3-2b3c-491e-bced-eeaa33db5ab1.jpeg)

**Comment by Axarva** [comment]
No, not just this much. 
Issue these commands:
`rm ~/.local/share/xorg/Xorg.0.log`
`startx`

Then upload the file `~/.local/share/xorg/Xorg.0.log`. (this will refresh the logs.)

**Comment by Gray-Zero** [comment]
See it's a big file and it's on my computer and I can only take a photo of it ![image](https://user-images.githubusercontent.com/62302371/126174503-1ad21f48-42b7-4dde-977b-ca1c4384fc57.jpeg)

**Comment by Axarva** [comment]
Try doing the following: 
`mv ~/.xmonad/xmonad.hs ~/.xmonad/xmonad.hs.bak`
`xmonad --recompile`

Then, try `startx`

**Comment by Gray-Zero** [comment]
Look ![image](https://user-images.githubusercontent.com/62302371/126176680-4dfd4fc4-2a9e-4f37-9159-aaa324cd0bd5.jpeg)

**Comment by Axarva** [comment]
Alright
Create a new `~/.xmonad/xmonad.hs` and add the following in it:
```hs
import XMonad

main = xmonad defaultConfig
        { modMask = mod4Mask -- Use Super instead of Alt
        , terminal = "alacritty"
        -- more changes
        }
```
Save the file, issue `xmonad --recompile`, then `startx`.

**Comment by Gray-Zero** [comment]
I did that but it does not work

**Comment by Gray-Zero** [comment]
startx error

**Comment by Gray-Zero** [comment]
Startx does not work xmonad worked

**Comment by Gray-Zero** [comment]
Yep

**Comment by Axarva** [comment]
Well then
`mv ~/.xmonad/xmonad.hs.bak ~/.xmonad/xmonad.hs`
`xmonad --recompile`

I cannot make head or tails of this. Is your driver configuration proper? I suggest looking at old threads of the problem in Arch or other distro forums and trying out solutions.
Will comment if I can find anything that might be helpful.

**Comment by Gray-Zero** [comment]
Oh ok thanks so much : D I will try resetting arch

**Comment by redgloboli** [comment]
i had a smiliar issue as i copied the export line from github and the problem was that instead of using PATH='$PATH:/home/user/bin' i had to set PATH="$PATH:/home/user/bin", after that it worked.

**Comment by Gray-Zero** [comment]
Startx does not work for me but I am on to something

**Comment by Axarva** [comment]
Seems like this issue is really popping up on Arch Linux. I'm not sure why though...

**Comment by Gray-Zero** [comment]
I fixed it I had to reinstall Arch and xorg

**Comment by Axarva** [comment]
That’s great! So it was an issue with xorg after all.. closing.
