### ISSUE TITLE
spawn programs on different workspaces on start

### ISSUE THREAD

**Issue by redgloboli** [Axarva/dotfiles-2.0#77]
Hi,

i'm fairly new to tiling windows managers and haskell to mention that at first ;)

I got almost everything i wanted to achieve, dunno if it's done right, but it works :)

My problem:

I can't wrap my head around how i may start programs on start on my preferred workspaces.

I've read about XMonad.Actions.SpawnOn and tried that, but it doesn't work as expected, it always starts on my current workspace. 

So before i add more stuff to the config which isn't really needed may ask what is the intended way to spawn apllications on the different workspaces?

Thanks for creating this scripts & configs !!

**Comment by Axarva** [comment]
Well, here's the required configs:

![image](https://user-images.githubusercontent.com/66304313/126437432-f2748064-1857-4b92-a5f8-279b027c9ba8.png)

The numbers after backslashes are just desktop names. If you're using these configs, adding these lines should let you spawn programs on your workspaces. Modify the `classname` field with the classnames of your programs.

**Comment by Axarva** [comment]
I've closed this for now. Comment again and I'll reopen. :)
