### ISSUE TITLE
Xmonad not starting up.

### ISSUE THREAD

**Issue by meehirmanitrips** [Axarva/dotfiles-2.0#78]
**Describe the bug**
Whenever i boot up my laptop and type startx it just gives me some weird output and not start xmonad like it used to do.
This problem started after i recently updated yay. 

**Screenshots**
![20210721_201627](https://user-images.githubusercontent.com/85008455/126512607-50df3968-7d1b-42e6-87b5-1d0286aa3820.jpg)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by Axarva** [comment]
Seems like some package is breaking xmonad. I’ll have to experiment on this.

**Comment by Axarva** [comment]
Try using a minimal xmonad.hs for the meantime. Go through #73 for instructions. If the issue persists. this issue is of the `xmonad` package on Arch/AUR repositories. If it works, it is this repository's issue.

**Comment by Axarva** [comment]
Sorry, wrong button :)

**Comment by redgloboli** [comment]
it's the same username on the screenshots!?

**Comment by Axarva** [comment]
#75 confirms that this is related to xorg rather than this setup. I suggest you go through some resources online, reinstall xorg and try again. Will be closing in the meantime. Do comment if you feel the need to reopen this issue. Thanks!
