### ISSUE TITLE
How do i delete this version of xmonad

### ISSUE THREAD

**Issue by meehirmanitrips** [Axarva/dotfiles-2.0#79]
If i want to delete this version of xmonad and all the things downloaded along with this(all except allacritty and dunst) then how do i do it.

**Comment by Axarva** [comment]
Remove the configs you don’t want.

To remove xmonad, remove ~/.xmonad/xmonad.hs

To remove rofi, remove ~/.config/rofi/

And so on.

**Comment by meehirmanitrips** [comment]
But that will only remove the configs right.....it won't delete xmonad completely right

**Comment by Axarva** [comment]
Right.

**Comment by Axarva** [comment]
Before doing so, I suggest you to try a minimal xmonad config so that we can at least get a clue where this issue arises from.

**Comment by meehirmanitrips** [comment]
I already have dwm and i am currently using that as the xmonad is not starting up........so i was wondering if just in case it doesn't start to work anytime soon or if it takes a lot of work to fix it then i will have to delete xmonad and the rest of the things that was downloaded along with it like paru, eww, and the other stuffs as they will be taking unnecessary space.
So if have to do then what will be the process to remove them completely.

**Comment by Axarva** [comment]
Remove your entire ~/bin directory unless you have added something there.
Remove the clone of this repo.

Go through the install script to see what else has been installed and remove them accordingly, since listing them out here is extremely inefficient.

**Comment by meehirmanitrips** [comment]
Got it thank you so much

**Comment by Axarva** [comment]
Well then, closing. Please do try to use a minimal xmonad to see if it works, as that will be of help to this repository.
