### ISSUE TITLE
Dont know what to do

### ISSUE THREAD

**Issue by berserkt** [Axarva/dotfiles-2.0#80]
**Describe the bug**
I was following a guide on YT because I'm new to linux and was wanting to install Xmonad, I did all the steps shown in the video but after the line "XMonad recompilation process exited with success!" it stops building while in the video it asks if you want to change your shell to zsh.

**Expected behavior**
For it to ask me if I wanted to change my default shell to zsh 

**Screenshots**
![image](https://user-images.githubusercontent.com/87779458/126541396-f2685c9d-8598-4edb-9d4a-696dc16c0861.png)

**Desktop (please complete the following information):**
 - OS: Running Arch Linux on a VM on Wiindows

**Comment by Axarva** [comment]
The video is a little outdated. The setup is no longer shell-dependent, so you can just add the “export..” line into your .bashrc, use your .xinitrc to launch xmonad and go on with your daily use.

**Comment by Axarva** [comment]
If you do want zsh, install oh-my-zsh, and you’ll be good to go.

**Comment by Axarva** [comment]
Will be closing since this isn't an issue at all. It's just the script being a bit minimal :)
