### ISSUE TITLE
Support for other monitor resolutions

### ISSUE THREAD

**Issue by Shahab96** [Axarva/dotfiles-2.0#82]
Currently this project only supports 1920x1080 and 1366x768 resolutions. It might be worth the effort to make the config files more dynamic to adjust to any resolution screen. Relatively problematic for me on my ultra-wide since it's 5120x1440 (which introduces yet another issue due to the aspect ratio being much different than 2560x1440) I'd be willing to work on this as well though I'm not as familiar with the configs.

**Comment by Axarva** [comment]
Well, yep, this has been a TODO for a long time. I’ll begin work on this soon, although cannot say when I’ll finish.

**Comment by Shahab96** [comment]
I'm happy to do this as well if you haven't got time or capacity.

**Comment by Axarva** [comment]
Sure! (That is, if it doesn’t bother you.)

The main things that need to be changed will be the font sizes and window sizes for the widgets and a little with the tint2 bar. 

Thank you so much though.. time gets hard to manage when you need to apply to universities :)

**Comment by Shahab96** [comment]
Yeah no problem, feel free to assign this issue to me. I'll test out on my fork and make a PR when it's ready.

**Comment by Axarva** [comment]
Done!

**Comment by Shahab96** [comment]
After discussion offline we've decided to wait for s-expressions to be implemented into eww before proceeding with this issue.

https://github.com/elkowar/eww/discussions/206

**Comment by Eason0210** [comment]
Hope to support 2560x1440 resolution in the future.

**Comment by elli0t43** [comment]
hope for 1600x900 support in the future

**Comment by s0lst1ce** [comment]
I believe #152 is a progress toward this?

**Comment by Axarva** [comment]
Yes, it is, although I'm still waiting for the PR creator to send in a screenshot just to see how the configuration looks before merging it.

**Comment by s0lst1ce** [comment]
@Axarva so I've installed your dotfiles on a computer on mine which I connected to one of my WQHD monitor. I've done this with the branch of the PR #152 . What kind of screenshot would you like?

**Comment by Shahab96** [comment]
This issue is stale.
