### ISSUE TITLE
Installation fails to proceed after selecting AUR helper

### ISSUE THREAD

**Issue by Shahab96** [Axarva/dotfiles-2.0#84]
**Describe the bug**
While testing stuff out on my desktop I ran ./install-on-arch.sh and made it to the aur helper prompt. Upon responding no (because I already have paru installed), the installation failed with the error

```bash
./install-on-arch.sh: line 101: -S: command not found
```

**To Reproduce**
1. Run ./install-on-arch.sh
2. Select your AUR helper
3. Respond no to installing the helper

**Expected behavior**
Installation should proceed to the end

**Screenshots**
![Screenshot_2021-07-22-11_3840x1080](https://user-images.githubusercontent.com/826895/126722594-2a9a99ee-f636-4026-977d-58e7615f2ae4.png)

**Desktop (please complete the following information):**
 - OS:
[neofetch.txt](https://github.com/Axarva/dotfiles-2.0/files/6865950/neofetch.txt)

**Comment by Shahab96** [comment]
Feel free to assign this one to me as well.

**Comment by Shahab96** [comment]
It seems that the selection for the helper is not actually being preserved.

After checking out the code it looks like the $HELPER variable is not in scope outside of the case statement

#https://github.com/Axarva/dotfiles-2.0/blob/3699ab780ababfc3b955906e371be70fd20de88b/install-on-arch.sh#L73-L84

Since we're using paru as the default we might be able to get away with setting HELPER to paru outside the case statement to make it's scope be the entire file.

**Comment by Axarva** [comment]
Yep, maybe setting HELPER as paru on top of the file will do the trick. I'm not sure why the case expression doesn't fully work though...

**Comment by Axarva** [comment]
Well, since this is done, closing.
