### ISSUE TITLE
adding how to change symbols in the taskbar to the readme

### ISSUE THREAD

**Issue by redgloboli** [Axarva/dotfiles-2.0#90]
Hi,

maybe a small howto should be added to the readme how to change the symbols on the taskbar?

I , for example, used kcharselect selected Iosevka font, selected misc, selected reserved for private use and changed the numbers accordingly in my xmonad.hs.

**Comment by Axarva** [comment]
That isn't really within the scope of this repository though.
In case of further issues I'll point them to this issue so that this serves as a precedent. 

Closing.
