### ISSUE TITLE
Stuff to replace for systemd not listed in readme

### ISSUE THREAD

**Issue by BlueskyFR** [Axarva/dotfiles-2.0#91]
In the readme, more precisely in the Arch installation section, it is mentionned to replace some stuff in the repo once cloned if the user is using systemd.
However, the systemd section of the readme file does not exist.

- Why would there be some stuff to replace for systemd?
- Either way, the section has to be created OR the links to it have to be deleted as they are pointing towards nothing right now.

Thanks for your work!

**Comment by Axarva** [comment]
The setup was modified to suit systemd instead of OpenRC a little while ago. Thank you for bringing this to attention. I’ll fix this soon.

**Comment by Kellegram** [comment]
@Axarva I removed those mentions from readme :thinking: Were they not removed from the extra branch or I somehow brainfarted and re-added them :laughing:

**Comment by Axarva** [comment]
Could be… I’m not sure either.

**Comment by Kellegram** [comment]
@Axarva So I was browsing unclosed issues that I participated in. Isn't this one long done? :joy: I haven't seen this config in a while, not sure if anything changed (I was so confused why my rofi theme broke tho and accidentally found the solution via your commit so yay!)

**Comment by Axarva** [comment]
Finally done.
