### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by KavyanshJain** [Axarva/dotfiles-2.0#92]
Hey! First of all a great wm
I doesn't know much about configuration, so can you help me to change the usernames everywhere from Axarva to the one I want.
And how to change default terminal from alacritty to kitty.
And how can I config the widgets to use them with spotify like apps

**Comment by redgloboli** [comment]
for eww it's in ~/.config/eww/eww.xml, don't know where else :)

xmonad terminal is set in ~/.xmonad/xmonad.hs, lookf for myTerminal = "alacritty"

for the widgets i think you should read the eww documentation. https://elkowar.github.io/eww/

**Comment by Axarva** [comment]
Changing usernames in rofi will need editing the prompts in `~/.config/rofi`

**Comment by Axarva** [comment]
I’ll assume there aren’t more questions. Feel free to comment if you have some. Closing.
