### ISSUE TITLE
wrong script for logout in full eww 1920

### ISSUE THREAD

**Issue by redgloboli** [Axarva/dotfiles-2.0#93]
in https://github.com/Axarva/dotfiles-2.0/blob/main/config/eww-1920/eww.xml

the logout command in full panel is linked to shutdown.sh -> button class="logout-full" onclick="~/.config/eww/scripts/shutdown.sh"></button

it's fine in 1366

**Comment by Axarva** [comment]
Fixed in 541a9458fd82904bf9eb00b72445725827f4801f. Thanks!
