### ISSUE TITLE
Search in eww not available

### ISSUE THREAD

**Issue by CyberBishop** [Axarva/dotfiles-2.0#95]
The search in eww is meant to launch launcher.sh which is meant  to be located in ~/bin/launcher.sh but I don't have launcher.sh

**Comment by Axarva** [comment]
For now, create a ~/bin/launcher.sh and add the line
rofi -no-lazy-grab -show drun -modi run,drun,window -theme $HOME/.config/rofi/launcher/style -drun-icon-theme "candy-icons"

**Comment by CyberBishop** [comment]
alright thanks

**Comment by Eason0210** [comment]
It worked. But I think it is more convinient to use Mod+o instead.

**Comment by CyberBishop** [comment]
> It worked. But I think it is more convinient to use Mod+o instead.

this is a temporary fix, I think a better search feature is going to be there later

**Comment by Axarva** [comment]
Added the fix. This search will migrate to eww itself natively once it’s supported, although it’s unlikely that’ll happen.
