### ISSUE TITLE
Floating windows by default

### ISSUE THREAD

**Issue by CyberBishop** [Axarva/dotfiles-2.0#96]
Is it possible to have the windows floating by default then if I want to tile I will press win + t key

**Comment by Axarva** [comment]
https://bbs.archlinux.org/viewtopic.php?id=160550

Refer to this thread. I haven't done this by myself, so I am not sure if it will work. Good luck!

**Comment by CyberBishop** [comment]
thanks

**Comment by CyberBishop** [comment]
is there any way I can make the apps open bigger and close the dock then the dock comes back when I close the app
