### ISSUE TITLE
Won't start on VM showing message about X.Org. No Error messages.

### ISSUE THREAD

**Issue by 573rn-1i** [Axarva/dotfiles-2.0#97]
![image](https://user-images.githubusercontent.com/54333645/129438173-2a932c32-0c6e-4ca8-91f5-bb47d19c22f2.png)

**Comment by Axarva** [comment]
Are you sure your .xinitrc is fine?

**Comment by Axarva** [comment]
Any updates on this?

**Comment by n2bhy** [comment]
Having the same problem, xinitrc is fine.

**Comment by Axarva** [comment]
Could you post the contents of your xinitrc file? Also, are you sure you installed xmonad correctly? What happens if you try running xmonad with a display manager?
