### ISSUE TITLE
Xorg-xbacklight and acpilight are in conflict

### ISSUE THREAD

**Issue by Kritiqual** [Axarva/dotfiles-2.0#98]
Hi as the title says, i have that problem after the step to install the appropriate video driver, so i can't proceed, can you help me fix this, thanks!

**Comment by Axarva** [comment]
Either uninstall acpilight or don’t install xorg-xbacklight.
Is there a reason why you chose acpilight?

**Comment by Axarva** [comment]
Any updates?

**Comment by Kritiqual** [comment]
oh forgot to update, i uninstall acpilight and using xorg-xbacklight, it's works fine
